import type { Locale } from '@/i18n';

/**
 * Copy da home nova, especificada em `docs/nova-home-binno.md` (05/09/2026) e
 * prototipada em `docs/nova-home-binno.html`. Substitui inteiramente a copy
 * anterior — não há campo antigo mantido por compatibilidade, porque só
 * `src/pages/Index.tsx`, `src/pages/Demo.tsx`, `src/components/marketing/
 * BinnoDemoCockpit.tsx`, `PublicMarketingNav.tsx` e `src/pages/Review.tsx` lêem
 * este módulo, e todos foram conferidos antes desta reescrita.
 *
 * NOMES DE CHAVE: a especificação pede que `maps`, `alerts`, `demo` e
 * `pricing` sejam REAPROVEITADOS com conteúdo novo (a seção 2 "O problema" mora
 * em `maps`, a seção 3 "Como funciona" mora em `alerts`), e só `avisos`,
 * `prova`, `segments`, `compare`, `honest`, `faq` e `finalCta` são chaves
 * novas. Manter os nomes assim, mesmo que soem descolados do conteúdo — é o
 * que o documento manda, e ele é a fonte da verdade.
 *
 * `avisos` (seção 3b, "Você não precisa vigiar o Google") entrou em
 * 05/09/2026, depois do resto da home nova já estar pronto: o Marcelo notou
 * que a página dizia que o Binno avisa mas nunca listava o quê. `itens` são
 * os tipos de aviso que existem de verdade na fila (`whatsapp_outbox.kind`,
 * ver comentário em `src/pages/Index.tsx`); `derrubando` e `ajudando` usam o
 * cenário ilustrativo do Bistrô Horizonte (`illustrativeDemoSnapshot.ts`),
 * marcado como exemplo na tela, nunca como dado real. Os sete assuntos de
 * `temasNote` são os de `topicLabel` em
 * `supabase/functions/_shared/experimentalApifyCollection.ts`.
 *
 * PREÇO: NUNCA por extenso.
 *
 * `scripts/check-um-preco-um-sitio.mjs` varre `src/**` à procura de `R$` a
 * seguir de dígito e recusa o verify se achar. Onde a copy cita um preço, esta
 * copy usa `{promo}`, `{regular}` ou `{vagas}` — substituídos em tempo de
 * render por `comVagas()` (`src/lib/precoBinno.ts`, com `replaceAll`, porque
 * mais de uma frase repete o mesmo marcador duas vezes).
 *
 * `hero.primary` e `pricing.cta` têm o mesmo texto (a prévia repete o CTA no
 * hero e no plano) mas são campos independentes, como no documento — não um
 * reaproveita o outro. `hero.primary` também é o CTA de `src/pages/Demo.tsx`,
 * por isso aquele ficheiro chama `comVagas()` também, e não só este.
 *
 * CONTEÚDO REAL, NÃO TRADUZIDO: o nome da cliente ("Mesquita"), o comentário
 * dela e a resposta do proprietário na animação do hero não vivem aqui — são
 * constantes em `HeroAnimado.tsx`, porque são a mesma avaliação real que
 * aparece no print de `prova.imageCaption` (`public/marketing/
 * prova-avaliacao-google.jpg`). Traduzir as palavras de uma cliente real para
 * vender a um visitante inglês seria inventar uma citação.
 */
export type MarketingCopy = {
  locale: Locale;
  nav: { howItWorks: string; capabilities: string; price: string; demo: string; login: string; start: string };
  pricing: {
    promoLabel: string; promoNote: string; eyebrow: string;
    oldPrice: string; newPrice: string; priceSuffix: string; loteNote: string;
    cta: string; hint: string; features: string[];
  };
  hero: {
    eyebrow: string; title: string; titleEmphasis: string; body: string;
    primary: string; secondary: string; micro: string;
    proof: Array<{ value: string; label: string }>;
    phoneAriaLabel: string;
    chatSystem: string; chatNoticeIntro: string; chatRatingLabel: string; chatRatingValue: string;
    chatCustomerLabel: string; chatCommentLabel: string; chatDraftIntro: string; chatInstruction: string;
    chatButton: string; chatConfirmedTitle: string; chatConfirmedBody: string;
    googleReviewerMeta: string; googleLike: string; googleShare: string;
    googleReplyLabel: string; googleReplyTime: string;
    timerLabel: string; replayLabel: string; headerName: string; headerBadge: string;
  };
  /** "O problema": a cena do cliente calado mais os três números com fonte. */
  maps: {
    eyebrow: string; title: string; body: string;
    stats: Array<{ value: string; suffix: string; body: string }>;
    sourceLabel: string; sourceText: string; sourceLinks: Array<{ label: string; href: string }>;
  };
  /** "Como funciona": os três pilares. */
  alerts: { eyebrow: string; title: string; items: Array<{ title: string; body: string }> };
  /**
   * "Você não precisa vigiar o Google" (seção 3b, nova em 05/09/2026). Entra
   * entre "Como funciona" e "Isso não é mockup". Coluna 1 lista os avisos
   * reais do WhatsApp (`itens`, um por `kind` de `whatsapp_outbox`); coluna 2
   * mostra o que o painel lê (`derrubando` e `ajudando`), com o cenário
   * ilustrativo do Bistrô Horizonte marcado como exemplo na tela.
   */
  avisos: {
    eyebrow: string; title: string;
    entregaTitle: string;
    itens: { title: string; body: string }[];
    entregaNote: string;
    temasTitle: string; temasBody: string;
    derrubando: { rotulo: string; tema: string; body: string; frase: string };
    ajudando: { rotulo: string; tema: string; body: string; frase: string };
    temasNote: string;
  };
  /** "Isso não é mockup": print real do Google mais a linha do tempo. */
  prova: {
    eyebrow: string; title: string; body: string; imageCaption: string;
    steps: Array<{ tag: string; title: string; body: string }>;
  };
  segments: { eyebrow: string; title: string; items: Array<{ number: string; title: string; body: string }> };
  demo: { eyebrow: string; title: string; body: string; label: string; primary: string };
  compare: {
    eyebrow: string; title: string; columnBefore: string; columnAfter: string;
    rows: Array<{ before: string; after: string }>;
  };
  honest: {
    eyebrow: string; title: string; body: string; note: string; link: string; linkHref: string;
    rules: Array<{ ok: boolean; title: string; body: string }>;
  };
  faq: { eyebrow: string; title: string; items: Array<{ question: string; answer: string }> };
  finalCta: { eyebrow: string; title: string; body: string; cta: string; micro: string };
  footer: { body: string; demo: string; terms: string; privacy: string };
  /**
   * O contacto directo, pedido por Marcelo em 02/09/2026 para começar a
   * prospecção. `mensagemDaVenda` já vai escrita na conversa e diz de onde a
   * pessoa veio; `mensagemDoNegocio` diz o mesmo a partir da página do QR.
   *
   * FORMATO EXACTO EXIGIDO: `scripts/check-marca-e-contacto.mjs` procura o
   * literal `contacto: { rotulo: '...', rotuloCurto: '...', mensagemDaVenda:
   * '...', mensagemDoNegocio: '...' }`, numa linha só, três vezes. Mudar a
   * pontuação ou quebrar a linha faz o guarda deixar de encontrar os três
   * idiomas e falhar.
   */
  contacto: { rotulo: string; rotuloCurto: string; mensagemDaVenda: string; mensagemDoNegocio: string };
};

const COPY: Record<Locale, MarketingCopy> = {
  'pt-BR': {
    locale: 'pt-BR',
    nav: { howItWorks: 'Como funciona', capabilities: 'Para quem é', price: 'Plano', demo: 'Demonstração', login: 'Entrar', start: 'Garantir R$ {promo}/mês' },
    pricing: { promoLabel: 'Lote fundador:', promoNote: 'R$ {promo}/mês para as {vagas} primeiras assinaturas. Depois, R$ {regular}/mês.', eyebrow: 'Plano fundador Binno', oldPrice: 'R$ {regular}', newPrice: 'R$ {promo}', priceSuffix: '/mês', loteNote: 'As {vagas} primeiras assinaturas mantêm esse preço enquanto seguirem ativas.', cta: 'Garantir preço fundador: R$ {promo}/mês', hint: 'Para negócios no Brasil. O país onde o negócio opera é confirmado no cadastro e validado no pagamento.', features: ['Aviso no WhatsApp a cada nova avaliação, com a resposta já escrita', 'Publicação no Google com um toque, sem abrir painel', 'Canal de mensagem direta para o cliente falar com você antes', 'QR Codes para balcão, mesas e comanda', 'Fila de respostas no painel, quando você quiser editar antes', 'Leitura da reputação e o que mudou na semana', 'Sem fidelidade: cancele quando quiser'] },
    hero: { eyebrow: 'Binno para negócios locais', title: 'Sua avaliação no Google chega no WhatsApp.', titleEmphasis: 'Você responde com um toque.', body: 'O Binno te avisa a cada nova avaliação com a resposta já escrita. Você lê, aprova com um toque, e ela aparece no seu perfil do Google. Sem abrir painel, sem computador, sem deixar o cliente esperando.', primary: 'Garantir preço fundador: R$ {promo}/mês', secondary: 'Ver a demonstração', micro: 'Sem formulário antes de pagar · Cancele quando quiser · Sem fidelidade', proof: [{ value: '21 s', label: 'do toque à resposta publicada, medido em 04/09' }, { value: '0', label: 'painéis pra abrir no dia a dia' }, { value: '100%', label: 'das respostas revisadas por você' }], phoneAriaLabel: 'Simulação da conversa no WhatsApp, com o texto real da mensagem do Binno', chatSystem: 'Esta empresa usa um serviço seguro da Meta para gerenciar esta conversa.', chatNoticeIntro: 'Você recebeu uma avaliação nova no seu Perfil da Empresa no Google.', chatRatingLabel: 'Nota', chatRatingValue: '4 de 5', chatCustomerLabel: 'Cliente', chatCommentLabel: 'Comentário', chatDraftIntro: 'Preparamos esta resposta:', chatInstruction: 'Toque no botão abaixo para publicar a resposta no seu perfil.', chatButton: 'Publicar no Google', chatConfirmedTitle: 'Publicada no Google.', chatConfirmedBody: 'A resposta já aparece no seu perfil, abaixo da avaliação de Mesquita.', googleReviewerMeta: 'Local Guide · 54 avaliações · 1 foto', googleLike: 'Gostei', googleShare: 'Compartilhar', googleReplyLabel: 'Resposta do proprietário', googleReplyTime: 'agora', timerLabel: 'Do toque ao Google:', replayLabel: 'Ver de novo', headerName: 'Binno · Assessor do Google', headerBadge: 'serviço oficial da Meta' },
    maps: { eyebrow: 'O problema', title: 'Quem escolhe onde comprar olha a sua nota antes de te conhecer.', body: 'Cliente insatisfeito quase nunca reclama na hora. Vai embora calado e escreve depois, no Google, onde todo mundo vê. E quem lê decide em segundos: não é o produto, não é o preço na porta, é a nota que aparece antes de a pessoa entrar.', stats: [{ value: '96', suffix: '%', body: 'leem avaliações no Google antes de escolher uma loja física.' }, { value: '93', suffix: '%', body: 'já desistiram de uma compra depois de ler avaliações negativas.' }, { value: '9', suffix: ' em 10', body: 'descartam empresas com nota abaixo de 4 estrelas. 40% só consideram acima de 4,5.' }], sourceLabel: 'Fonte', sourceText: 'Pesquisa Decisão Local 2025, Harmo e Reclame Aqui, 1.591 entrevistados no Brasil. Noticiada em:', sourceLinks: [{ label: 'Relatório Harmo', href: 'https://harmo.me/relatorios/decisao-local' }, { label: 'Mercado&Consumo', href: 'https://mercadoeconsumo.com.br/26/03/2025/noticias-varejo/reclame-aqui-96-dos-consumidores-leem-avaliacoes-no-google-antes-de-comprar/' }, { label: 'Novo Varejo', href: 'https://novovarejo.com.br/avaliacoes-no-google-impactam-a-escolha-de-96-dos-consumidores/' }, { label: 'Meio&Mensagem', href: 'https://www.meioemensagem.com.br/marketing/reputacao-digital-como-as-avaliacoes-afetam-a-jornada-do-consumidor' }] },
    alerts: { eyebrow: 'Como funciona', title: 'Controle da sua reputação sem parar a operação.', items: [{ title: 'Da avaliação à resposta publicada, em segundos', body: 'Chegou avaliação no Google? O Binno te avisa no WhatsApp com uma resposta pronta, escrita a partir do que aquele cliente escreveu. Você lê, aprova com um toque, e ela é publicada no seu perfil.' }, { title: 'Escute antes do Google, não no lugar dele', body: 'O QR Code no balcão dá ao seu cliente um canal direto com a sua equipe. Quem teve um problema fala com você primeiro, e você resolve enquanto ainda dá tempo. O caminho para avaliar no Google continua sempre lá.' }, { title: 'Não seja pego de surpresa', body: 'Quando o número de avaliações cai, as notas baixas ganham espaço ou três pessoas citam a mesma coisa, o Binno explica o que mudou e o que dá pra fazer agora. Uma coisa por vez.' }] },
    avisos: { eyebrow: 'Você não precisa vigiar o Google', title: 'O Binno olha por você e te chama quando importa.', entregaTitle: 'O que chega no seu WhatsApp', itens: [{ title: 'Avaliação nova.', body: 'Com a resposta já escrita, pronta pra você aprovar.' }, { title: 'Notas baixas se concentrando num assunto.', body: '"A leitura recente encontrou 3 notas baixas e 3 menções a tempo de espera."' }, { title: 'Reclamação pelo QR Code, na hora.', body: 'Antes de virar avaliação pública. E o elogio também chega.' }, { title: 'Avaliação esperando resposta.', body: 'Pra nenhuma ficar dias sem retorno.' }, { title: 'Resumo da semana.', body: 'O que ajudou, o que atrapalhou, e uma coisa pra fazer.' }], entregaNote: 'Você escolhe quais avisos recebe, com que frequência e em qual número.', temasTitle: 'E o painel diz o porquê', temasBody: 'O Binno lê o que os clientes escrevem e separa os assuntos que derrubam a sua nota dos que sustentam ela. Cada um com a frase do cliente que prova.', derrubando: { rotulo: 'Está derrubando', tema: 'Tempo de espera', body: '3 pessoas citaram na mesma semana, todas com 1 ou 2 estrelas.', frase: '"O atendimento demorou mais do que o esperado."' }, ajudando: { rotulo: 'Está te ajudando', tema: 'Prato executivo', body: 'Aparece em 7 elogios. É isso que merece foto e destaque.', frase: '"Prato executivo excelente, voltarei com certeza."' }, temasNote: 'Assuntos que o Binno lê: atendimento, tempo de espera, comida, limpeza, preço, ambiente e entrega.' },
    prova: { eyebrow: 'Isso não é mockup', title: 'A resposta que aparece no seu Google depois de um toque no WhatsApp.', body: 'Sem aplicativo pra instalar e sem painel pra abrir. O Binno lê a avaliação, escreve um rascunho a partir do que o cliente disse e te entrega tudo numa mensagem só. Você toca, e a resposta vai pro seu perfil.', imageCaption: 'Print real do perfil da Noá Digital no Google, 04/09/2026. Resposta publicada pelo WhatsApp, com um toque.', steps: [{ tag: 'passo 1', title: 'A avaliação entra no Google', body: 'Quatro estrelas, comentário curto, cliente real.' }, { tag: 'passo 2', title: 'O Binno te avisa no WhatsApp', body: 'Com o que o cliente escreveu e a resposta já pronta.' }, { tag: '1 toque', title: 'Você toca em "Publicar no Google"', body: 'Se quiser mudar o texto antes, o painel está a um link de distância.' }, { tag: '21 s depois', title: 'Publicada no seu perfil do Google', body: 'Quem publica é você, sempre. O Binno nunca publica sozinho.' }] },
    segments: { eyebrow: 'Para quem é', title: 'Todo negócio que acredita que o Google pode ajudar a vender.', items: [{ number: '01', title: 'Negócio local', body: 'Loja, comércio de bairro, quem atende no balcão do caixa. Um canal de escuta fácil e resposta rápida.' }, { number: '02', title: 'Gastronomia', body: 'Restaurantes, bares e cafés: resolva um pedido errado no privado antes que ele vire nota.' }, { number: '03', title: 'Saúde e bem-estar', body: 'Clínicas, consultórios, salões e estúdios: responda com agilidade e acolhimento.' }, { number: '04', title: 'Hospedagens', body: 'Pousadas, hotéis e aluguel por temporada: cada avaliação decide a próxima reserva.' }, { number: '05', title: 'Serviços', body: 'Oficinas, pet shops, assistências: perfil sempre ativo, sem tirar ninguém do serviço.' }] },
    demo: { eyebrow: 'Demonstração', title: 'Veja o Binno funcionando antes de criar conta.', body: 'Um exemplo completo, com dados ilustrativos: o aviso, a fila de respostas, a leitura da reputação e o que mudou na semana.', label: 'Demonstração ilustrativa', primary: 'Explorar a demonstração completa' },
    compare: { eyebrow: 'O que muda', title: 'Cuidar do Google do jeito tradicional custa cliente.', columnBefore: 'Hoje, sem o Binno', columnAfter: 'Com o Binno', rows: [{ before: 'Você só sabe da avaliação se lembrar de abrir o Google', after: 'Aviso no WhatsApp, na hora, com a resposta pronta' }, { before: 'Dias ou semanas para responder um comentário', after: 'Resposta publicada em segundos, do seu WhatsApp' }, { before: 'Abrir o painel do Google no computador', after: 'Aviso e aprovação com um toque, no celular' }, { before: 'O cliente insatisfeito só tem o Google para falar', after: 'Canal direto com a sua equipe pelo QR Code, antes de virar avaliação' }, { before: 'Você nunca sabe se uma avaliação virou um padrão', after: 'O Binno aponta o que mudou, com a frase do cliente que prova' }] },
    honest: { eyebrow: 'A regra que não muda', title: 'O Binno nunca esconde uma avaliação ruim.', body: 'Tem ferramenta que manda o cliente satisfeito pro Google e o insatisfeito pra um formulário privado. Isso se chama review gating, e a política do Google proíbe. Quem é pego pode ver avaliações apagadas, o perfil restrito e um aviso público na ficha dizendo que houve avaliação falsa.', note: 'No Binno o caminho pro Google aparece sempre, qualquer que seja a nota. Verificações automáticas no código impedem que isso mude.', link: 'Ler a política de avaliações do Google', linkHref: 'https://support.google.com/contributionpolicy/answer/7400114', rules: [{ ok: true, title: 'Cliente com 5 estrelas', body: 'Vê o botão de avaliar no Google.' }, { ok: true, title: 'Cliente com 1 estrela', body: 'Vê o mesmo botão de avaliar no Google. E pode, se quiser, também mandar um comentário privado pra você.' }, { ok: false, title: 'Perguntar "gostou?" antes de mostrar o Google', body: 'Não existe no Binno. É isso que o Google chama de review gating.' }] },
    faq: { eyebrow: 'Perguntas frequentes', title: 'O que todo dono pergunta antes de assinar.', items: [{ question: 'Como a mensagem direta evita comentários negativos no Google?', answer: 'Ela não impede ninguém de avaliar, e o Binno nunca esconde o caminho do Google. O que ela faz é te dar a chance de saber primeiro. Ao escanear o QR Code, o cliente pode mandar uma mensagem privada para a sua equipe; se algo deu errado, você resolve enquanto ele ainda está por perto.' }, { question: 'O Binno garante que minha nota no Google vai subir?', answer: 'Não. A nota depende do que o seu cliente viveu, e ninguém honesto promete mudá-la. O que o Binno garante é velocidade de resposta e um canal direto para que insatisfações contornáveis cheguem a você antes de chegarem ao Google.' }, { question: 'Preciso instalar algum aplicativo?', answer: 'Não. Depois de conectar seu Perfil da Empresa do Google ao Binno (uma vez só, pelo celular ou computador), responder avaliações acontece inteiramente no WhatsApp: você recebe o aviso, lê a resposta pronta e aprova com um toque.' }, { question: 'Preciso criar conta antes de assinar?', answer: 'Não. Você paga primeiro e cria seu acesso depois, na tela seguinte. Sem formulário no meio do caminho.' }, { question: 'O valor de R$ {promo}/mês muda depois?', answer: 'Não para você. Assinando no lote fundador, os R$ {promo} ficam travados na sua conta mesmo quando o preço voltar a R$ {regular}.' }] },
    finalCta: { eyebrow: 'Sua próxima avaliação chega hoje', title: 'Você vai responder em segundos ou em semanas?', body: 'Aviso no WhatsApp, resposta pronta, publicação com um toque. E um canal direto para o cliente falar com você antes de falar com o Google.', cta: 'Quero o Binno por R$ {promo}/mês', micro: 'Sem formulário antes de pagar · Cancele quando quiser · Sem fidelidade' },
    footer: { body: 'Assessoria de reputação para negócios locais.', demo: 'Demonstração', terms: 'Termos', privacy: 'Privacidade' },
    contacto: { rotulo: 'Falar no WhatsApp', rotuloCurto: 'Falar com o Binno', mensagemDaVenda: 'Olá! Vim pelo site do Binno e queria entender melhor como funciona.', mensagemDoNegocio: 'Olá! Vi o Binno numa página de avaliação e queria saber como funciona para o meu negócio.' },
  },
  'pt-PT': {
    locale: 'pt-PT',
    nav: { howItWorks: 'Como funciona', capabilities: 'Para quem é', price: 'Plano', demo: 'Demonstração', login: 'Entrar', start: 'Garantir R$ {promo}/mês' },
    pricing: { promoLabel: 'Lote fundador:', promoNote: 'R$ {promo}/mês para as {vagas} primeiras assinaturas. Depois, R$ {regular}/mês.', eyebrow: 'Plano de fundador Binno', oldPrice: 'R$ {regular}', newPrice: 'R$ {promo}', priceSuffix: '/mês', loteNote: 'As primeiras {vagas} assinaturas mantêm este preço enquanto se mantiverem ativas.', cta: 'Garantir preço de fundador: R$ {promo}/mês', hint: 'Para negócios no Brasil. O país onde o negócio opera é confirmado no registo e validado no pagamento.', features: ['Aviso no WhatsApp a cada nova avaliação, com a resposta já escrita', 'Publicação no Google com um toque, sem abrir painel', 'Canal de mensagem direta para o cliente falar consigo primeiro', 'Códigos QR para o balcão, mesas e conta', 'Fila de respostas no painel, quando quiser editar antes', 'Leitura da reputação e o que mudou na semana', 'Sem fidelização: cancele quando quiser'] },
    hero: { eyebrow: 'Binno para negócios locais', title: 'A sua avaliação no Google chega ao WhatsApp.', titleEmphasis: 'Responde com um toque.', body: 'O Binno avisa-o a cada nova avaliação com a resposta já escrita. Lê, aprova com um toque, e ela aparece no seu perfil do Google. Sem abrir painel, sem computador, sem deixar o cliente à espera.', primary: 'Garantir preço de fundador: R$ {promo}/mês', secondary: 'Ver a demonstração', micro: 'Sem formulário antes de pagar · Cancele quando quiser · Sem fidelização', proof: [{ value: '21 s', label: 'do toque à resposta publicada, medido a 04/09' }, { value: '0', label: 'painéis para abrir no dia a dia' }, { value: '100%', label: 'das respostas revistas por si' }], phoneAriaLabel: 'Simulação da conversa no WhatsApp, com o texto real da mensagem do Binno', chatSystem: 'Esta empresa utiliza um serviço seguro da Meta para gerir esta conversa.', chatNoticeIntro: 'Recebeu uma avaliação nova no seu Perfil da Empresa no Google.', chatRatingLabel: 'Nota', chatRatingValue: '4 de 5', chatCustomerLabel: 'Cliente', chatCommentLabel: 'Comentário', chatDraftIntro: 'Preparámos esta resposta:', chatInstruction: 'Toque no botão abaixo para publicar a resposta no seu perfil.', chatButton: 'Publicar no Google', chatConfirmedTitle: 'Publicada no Google.', chatConfirmedBody: 'A resposta já aparece no seu perfil, a seguir à avaliação de Mesquita.', googleReviewerMeta: 'Local Guide · 54 avaliações · 1 fotografia', googleLike: 'Gostei', googleShare: 'Partilhar', googleReplyLabel: 'Resposta do proprietário', googleReplyTime: 'agora', timerLabel: 'Do toque ao Google:', replayLabel: 'Ver de novo', headerName: 'Binno · Assessor do Google', headerBadge: 'serviço oficial da Meta' },
    maps: { eyebrow: 'O problema', title: 'Quem escolhe onde comprar olha a sua nota antes de o conhecer.', body: 'Um cliente insatisfeito quase nunca reclama na hora. Vai-se embora calado e escreve depois, no Google, onde todos veem. E quem lê decide em segundos: não é o produto, não é o preço à porta, é a nota que aparece antes de a pessoa entrar.', stats: [{ value: '96', suffix: '%', body: 'leem avaliações no Google antes de escolher uma loja física.' }, { value: '93', suffix: '%', body: 'já desistiram de uma compra depois de ler avaliações negativas.' }, { value: '9', suffix: ' em 10', body: 'descartam empresas com nota abaixo de 4 estrelas. 40% só consideram acima de 4,5.' }], sourceLabel: 'Fonte', sourceText: 'Estudo Decisão Local 2025, Harmo e Reclame Aqui, 1591 inquiridos no Brasil. Noticiado em:', sourceLinks: [{ label: 'Relatório Harmo', href: 'https://harmo.me/relatorios/decisao-local' }, { label: 'Mercado&Consumo', href: 'https://mercadoeconsumo.com.br/26/03/2025/noticias-varejo/reclame-aqui-96-dos-consumidores-leem-avaliacoes-no-google-antes-de-comprar/' }, { label: 'Novo Varejo', href: 'https://novovarejo.com.br/avaliacoes-no-google-impactam-a-escolha-de-96-dos-consumidores/' }, { label: 'Meio&Mensagem', href: 'https://www.meioemensagem.com.br/marketing/reputacao-digital-como-as-avaliacoes-afetam-a-jornada-do-consumidor' }] },
    alerts: { eyebrow: 'Como funciona', title: 'Controlo da sua reputação sem parar a operação.', items: [{ title: 'Da avaliação à resposta publicada, em segundos', body: 'Chegou uma avaliação ao Google? O Binno avisa-o no WhatsApp com uma resposta pronta, escrita a partir do que esse cliente escreveu. Lê, aprova com um toque, e ela é publicada no seu perfil.' }, { title: 'Ouça antes do Google, e não no lugar dele', body: 'O QR Code no balcão dá ao seu cliente um canal direto com a sua equipa. Quem teve um problema fala consigo primeiro, e resolve-o enquanto ainda há tempo. O caminho para avaliar no Google continua sempre lá.' }, { title: 'Não seja apanhado de surpresa', body: 'Quando o número de avaliações cai, as notas baixas ganham espaço ou três pessoas mencionam o mesmo problema, o Binno explica o que mudou e o que pode fazer agora. Uma coisa de cada vez.' }] },
    avisos: { eyebrow: 'Não precisa de vigiar o Google', title: 'O Binno olha por si e avisa-o quando importa.', entregaTitle: 'O que chega ao seu WhatsApp', itens: [{ title: 'Avaliação nova.', body: 'Com a resposta já escrita, pronta para aprovar.' }, { title: 'Notas baixas a concentrarem-se num assunto.', body: '"A leitura recente encontrou 3 notas baixas e 3 menções a tempo de espera."' }, { title: 'Reclamação pelo código QR, na hora.', body: 'Antes de se tornar avaliação pública. E o elogio também chega.' }, { title: 'Avaliação à espera de resposta.', body: 'Para nenhuma ficar dias sem resposta.' }, { title: 'Resumo da semana.', body: 'O que ajudou, o que atrapalhou, e uma coisa a fazer.' }], entregaNote: 'Escolhe que avisos recebe, com que frequência e em que número.', temasTitle: 'E o painel diz porquê', temasBody: 'O Binno lê o que os clientes escrevem e separa os assuntos que fazem baixar a sua nota dos que a sustentam. Cada um com a frase do cliente que o prova.', derrubando: { rotulo: 'Está a baixar', tema: 'Tempo de espera', body: '3 pessoas mencionaram-no na mesma semana, todas com 1 ou 2 estrelas.', frase: '"O atendimento demorou mais do que o esperado."' }, ajudando: { rotulo: 'Está a ajudar', tema: 'Prato executivo', body: 'Aparece em 7 elogios. É isso que merece fotografia e destaque.', frase: '"Prato executivo excelente, volto com certeza."' }, temasNote: 'Assuntos que o Binno lê: atendimento, tempo de espera, comida, limpeza, preço, ambiente e entrega.' },
    prova: { eyebrow: 'Isto não é um mockup', title: 'A resposta que aparece no seu Google depois de um toque no WhatsApp.', body: 'Sem aplicação para instalar e sem painel para abrir. O Binno lê a avaliação, escreve um rascunho a partir do que o cliente disse e entrega-lhe tudo numa única mensagem. Toca, e a resposta vai para o seu perfil.', imageCaption: 'Print real do perfil da Noá Digital no Google, 04/09/2026. Resposta publicada pelo WhatsApp, com um toque.', steps: [{ tag: 'passo 1', title: 'A avaliação entra no Google', body: 'Quatro estrelas, comentário curto, cliente real.' }, { tag: 'passo 2', title: 'O Binno avisa-o no WhatsApp', body: 'Com o que o cliente escreveu e a resposta já pronta.' }, { tag: '1 toque', title: 'Toca em "Publicar no Google"', body: 'Se quiser mudar o texto antes, o painel está a um link de distância.' }, { tag: '21 s depois', title: 'Publicada no seu perfil do Google', body: 'A publicação é sempre sua. O Binno nunca publica sozinho.' }] },
    segments: { eyebrow: 'Para quem é', title: 'Todo o negócio que acredita que o Google pode ajudar a vender.', items: [{ number: '01', title: 'Negócio local', body: 'Loja, comércio de bairro, quem atende ao balcão da caixa. Um canal de escuta fácil e resposta rápida.' }, { number: '02', title: 'Gastronomia', body: 'Restaurantes, bares e cafés: resolva um pedido errado em privado antes que se transforme numa avaliação.' }, { number: '03', title: 'Saúde e bem-estar', body: 'Clínicas, consultórios, salões e estúdios: responda com agilidade e simpatia.' }, { number: '04', title: 'Alojamento', body: 'Pensões, hotéis e alojamento local: cada avaliação decide a próxima reserva.' }, { number: '05', title: 'Serviços', body: 'Oficinas, lojas de animais e assistências técnicas: perfil sempre ativo, sem tirar ninguém do trabalho.' }] },
    demo: { eyebrow: 'Demonstração', title: 'Veja o Binno a funcionar antes de criar conta.', body: 'Um exemplo completo, com dados ilustrativos: o aviso, a fila de respostas, a leitura da reputação e o que mudou na semana.', label: 'Demonstração ilustrativa', primary: 'Explorar a demonstração completa' },
    compare: { eyebrow: 'O que muda', title: 'Cuidar do Google à moda antiga custa clientes.', columnBefore: 'Hoje, sem o Binno', columnAfter: 'Com o Binno', rows: [{ before: 'Só sabe da avaliação se se lembrar de abrir o Google', after: 'Aviso no WhatsApp, na hora, com a resposta pronta' }, { before: 'Dias ou semanas para responder a um comentário', after: 'Resposta publicada em segundos, a partir do seu WhatsApp' }, { before: 'Abrir o painel do Google no computador', after: 'Aviso e aprovação com um toque, no telemóvel' }, { before: 'O cliente insatisfeito só tem o Google para falar', after: 'Canal direto com a sua equipa pelo QR Code, antes de se transformar em avaliação' }, { before: 'Nunca sabe se uma avaliação se tornou um padrão', after: 'O Binno aponta o que mudou, com a frase do cliente que o prova' }] },
    honest: { eyebrow: 'A regra que não muda', title: 'O Binno nunca esconde uma avaliação má.', body: 'Há ferramentas que enviam o cliente satisfeito para o Google e o insatisfeito para um formulário privado. Chama-se review gating, e a política do Google proíbe-o. Quem é apanhado pode ver avaliações eliminadas, o perfil restringido e um aviso público na ficha a dizer que houve avaliações falsas.', note: 'No Binno o caminho para o Google aparece sempre, seja qual for a nota. Verificações automáticas no código impedem que isso mude.', link: 'Ler a política de avaliações do Google', linkHref: 'https://support.google.com/contributionpolicy/answer/7400114', rules: [{ ok: true, title: 'Cliente com 5 estrelas', body: 'Vê o botão para avaliar no Google.' }, { ok: true, title: 'Cliente com 1 estrela', body: 'Vê o mesmo botão para avaliar no Google. E pode, se quiser, enviar também um comentário privado.' }, { ok: false, title: 'Perguntar "gostou?" antes de mostrar o Google', body: 'Não existe no Binno. É a isso que o Google chama review gating.' }] },
    faq: { eyebrow: 'Perguntas frequentes', title: 'O que todo o dono pergunta antes de assinar.', items: [{ question: 'Como é que a mensagem direta evita comentários negativos no Google?', answer: 'Não impede ninguém de avaliar, e o Binno nunca esconde o caminho do Google. O que faz é dar-lhe a hipótese de saber primeiro. Ao ler o código QR, o cliente pode enviar uma mensagem privada à sua equipa; se algo correu mal, resolve-o enquanto ele ainda está por perto.' }, { question: 'O Binno garante que a minha nota no Google vai subir?', answer: 'Não. A nota depende do que o cliente viveu, e ninguém honesto promete mudá-la. O que o Binno garante é velocidade de resposta e um canal direto para que insatisfações contornáveis cheguem até si antes de chegarem ao Google.' }, { question: 'Preciso de instalar alguma aplicação?', answer: 'Não. Depois de ligar o seu Perfil da Empresa do Google ao Binno (uma única vez, pelo telemóvel ou computador), responder a avaliações acontece inteiramente no WhatsApp: recebe o aviso, lê a resposta pronta e aprova com um toque.' }, { question: 'Preciso de criar conta antes de assinar?', answer: 'Não. Paga primeiro e cria o seu acesso depois, no ecrã seguinte. Sem formulário pelo meio.' }, { question: 'O valor de R$ {promo}/mês muda depois?', answer: 'Não para si. Ao assinar no lote de fundadores, os R$ {promo} ficam fixos na sua conta mesmo quando o preço voltar a R$ {regular}.' }] },
    finalCta: { eyebrow: 'A sua próxima avaliação chega hoje', title: 'Vai responder em segundos ou em semanas?', body: 'Aviso no WhatsApp, resposta pronta, publicação com um toque. E um canal direto para o cliente falar consigo antes de falar com o Google.', cta: 'Quero o Binno por R$ {promo}/mês', micro: 'Sem formulário antes de pagar · Cancele quando quiser · Sem fidelização' },
    footer: { body: 'Assessoria de reputação para negócios locais.', demo: 'Demonstração', terms: 'Termos', privacy: 'Privacidade' },
    contacto: { rotulo: 'Falar no WhatsApp', rotuloCurto: 'Falar com o Binno', mensagemDaVenda: 'Olá! Vim pelo site do Binno e queria perceber melhor como funciona.', mensagemDoNegocio: 'Olá! Vi o Binno numa página de avaliação e queria saber como funciona para o meu negócio.' },
  },
  en: {
    locale: 'en',
    nav: { howItWorks: 'How it works', capabilities: "Who it's for", price: 'Plan', demo: 'Demo', login: 'Log in', start: 'Get R$ {promo}/month' },
    pricing: { promoLabel: 'Founding batch:', promoNote: 'R$ {promo}/month for the first {vagas} subscriptions. After that, R$ {regular}/month.', eyebrow: 'Binno founding plan', oldPrice: 'R$ {regular}', newPrice: 'R$ {promo}', priceSuffix: '/month', loteNote: 'The first {vagas} subscriptions keep this price for as long as they stay active.', cta: 'Lock in the founding price: R$ {promo}/month', hint: 'For businesses in Brazil. The country where the business operates is confirmed at sign-up and validated at payment.', features: ['A WhatsApp alert for every new review, with the reply already written', 'Publish to Google with one tap, no dashboard to open', 'A direct message channel for customers to talk to you first', 'QR codes for the counter, tables and the check', 'A reply queue in the dashboard, whenever you want to edit first', 'A reading of your reputation and what changed this week', 'No lock-in contract: cancel anytime'] },
    hero: { eyebrow: 'Binno for local businesses', title: 'Your Google review lands on WhatsApp.', titleEmphasis: 'You reply with one tap.', body: 'Binno alerts you to every new review with the reply already written. You read it, approve with one tap, and it appears on your Google profile. No dashboard, no computer, no keeping the customer waiting.', primary: 'Lock in the founding price: R$ {promo}/month', secondary: 'Watch the demo', micro: 'No form before you pay · Cancel anytime · No lock-in contract', proof: [{ value: '21 s', label: 'from tap to published reply, measured on 09/04' }, { value: '0', label: 'dashboards to open day to day' }, { value: '100%', label: 'of replies reviewed by you' }], phoneAriaLabel: "Simulation of the WhatsApp conversation, with Binno's real message text", chatSystem: 'This business uses a secure service from Meta to manage this conversation.', chatNoticeIntro: 'You got a new review on your Google Business Profile.', chatRatingLabel: 'Rating', chatRatingValue: '4 of 5', chatCustomerLabel: 'Customer', chatCommentLabel: 'Comment', chatDraftIntro: 'We drafted this reply:', chatInstruction: 'Tap the button below to publish the reply on your profile.', chatButton: 'Publish to Google', chatConfirmedTitle: 'Published on Google.', chatConfirmedBody: "The reply is already on your profile, right below Mesquita's review.", googleReviewerMeta: 'Local Guide · 54 reviews · 1 photo', googleLike: 'Like', googleShare: 'Share', googleReplyLabel: 'Response from the owner', googleReplyTime: 'just now', timerLabel: 'Tap to Google:', replayLabel: 'Watch again', headerName: 'Binno · Google Advisor', headerBadge: 'official Meta service' },
    maps: { eyebrow: 'The problem', title: 'Whoever decides where to buy checks your rating before they know you.', body: "An unhappy customer almost never complains on the spot. They leave quietly and write about it later, on Google, where everyone sees it. And whoever reads it decides in seconds: it isn't the product, it isn't the price on the door, it's the rating that shows up before the person even walks in.", stats: [{ value: '96', suffix: '%', body: 'read Google reviews before choosing a physical store.' }, { value: '93', suffix: '%', body: 'have given up on a purchase after reading negative reviews.' }, { value: '9', suffix: ' in 10', body: 'rule out businesses rated below 4 stars. Only 40% consider anything above 4.5.' }], sourceLabel: 'Source', sourceText: 'Decisão Local 2025 survey, Harmo and Reclame Aqui, 1,591 respondents in Brazil. Covered by:', sourceLinks: [{ label: 'Relatório Harmo', href: 'https://harmo.me/relatorios/decisao-local' }, { label: 'Mercado&Consumo', href: 'https://mercadoeconsumo.com.br/26/03/2025/noticias-varejo/reclame-aqui-96-dos-consumidores-leem-avaliacoes-no-google-antes-de-comprar/' }, { label: 'Novo Varejo', href: 'https://novovarejo.com.br/avaliacoes-no-google-impactam-a-escolha-de-96-dos-consumidores/' }, { label: 'Meio&Mensagem', href: 'https://www.meioemensagem.com.br/marketing/reputacao-digital-como-as-avaliacoes-afetam-a-jornada-do-consumidor' }] },
    alerts: { eyebrow: 'How it works', title: 'Control your reputation without stopping the day-to-day.', items: [{ title: 'From review to published reply, in seconds', body: "A review lands on Google? Binno alerts you on WhatsApp with a reply already written from what that customer said. You read it, approve with one tap, and it's published on your profile." }, { title: 'Listen before Google, not instead of it', body: "The QR code on the counter gives your customer a direct channel to your team. Whoever had a problem talks to you first, and you fix it while there's still time. The path to review on Google is always still there." }, { title: 'Never get caught off guard', body: 'When the number of reviews drops, low ratings gain ground, or three people mention the same thing, Binno explains what changed and what you can do about it now. One thing at a time.' }] },
    avisos: { eyebrow: "You don't need to watch Google", title: 'Binno watches for you and calls when it matters.', entregaTitle: 'What lands on your WhatsApp', itens: [{ title: 'A new review.', body: 'With the reply already written, ready for you to approve.' }, { title: 'Low ratings clustering around one topic.', body: '"The latest reading found 3 low ratings and 3 mentions of wait time."' }, { title: 'A complaint through the QR code, right away.', body: 'Before it becomes a public review. And the compliment arrives too.' }, { title: 'A review waiting for a reply.', body: "So none of them go days without an answer." }, { title: 'The weekly summary.', body: 'What helped, what hurt, and one thing to do.' }], entregaNote: 'You choose which alerts you get, how often, and on which number.', temasTitle: 'And the dashboard tells you why', temasBody: "Binno reads what customers write and separates the topics dragging your rating down from the ones holding it up. Each one with the customer's own words as proof.", derrubando: { rotulo: 'Dragging it down', tema: 'Wait time', body: '3 people mentioned it in the same week, all with 1 or 2 stars.', frase: '"The service took longer than expected."' }, ajudando: { rotulo: 'Helping you', tema: 'Executive plate', body: "Shows up in 7 compliments. That's what deserves a photo and the spotlight.", frase: '"Excellent executive plate, I will be back for sure."' }, temasNote: 'Topics Binno reads: service, wait time, food, cleanliness, price, atmosphere, and delivery.' },
    prova: { eyebrow: "This isn't a mockup", title: 'The reply that shows up on your Google profile after one tap on WhatsApp.', body: 'No app to install and no dashboard to open. Binno reads the review, drafts a reply from what the customer said and hands you all of it in a single message. You tap, and the reply goes to your profile.', imageCaption: "Real screenshot of Noá Digital's Google profile, 09/04/2026. Reply published from WhatsApp, with one tap.", steps: [{ tag: 'step 1', title: 'The review lands on Google', body: 'Four stars, a short comment, a real customer.' }, { tag: 'step 2', title: 'Binno alerts you on WhatsApp', body: 'With what the customer wrote and the reply already drafted.' }, { tag: '1 tap', title: 'You tap "Publish to Google"', body: 'If you want to edit it first, the dashboard is one link away.' }, { tag: '21 s later', title: 'Published on your Google profile', body: "You're always the one publishing. Binno never publishes on its own." }] },
    segments: { eyebrow: "Who it's for", title: 'Every business that believes Google can help it sell.', items: [{ number: '01', title: 'Local business', body: 'Shops, neighborhood stores, whoever works the counter. An easy listening channel and a fast reply.' }, { number: '02', title: 'Food & drink', body: 'Restaurants, bars and cafés: fix a wrong order privately before it becomes a rating.' }, { number: '03', title: 'Health & wellness', body: 'Clinics, practices, salons and studios: reply with speed and warmth.' }, { number: '04', title: 'Lodging', body: 'Inns, hotels and short-term rentals: every review decides the next booking.' }, { number: '05', title: 'Services', body: 'Repair shops, pet stores, technical assistance: an always-active profile, without pulling anyone off the job.' }] },
    demo: { eyebrow: 'Full demo', title: 'See Binno working before you create an account.', body: 'A complete illustrative scenario: the alert, the reply queue, the reputation reading and what changed this week.', label: 'Illustrative demo', primary: 'Explore the full demo' },
    compare: { eyebrow: 'What changes', title: 'Managing Google the old way costs you customers.', columnBefore: 'Today, without Binno', columnAfter: 'With Binno', rows: [{ before: 'You only find out about a review if you remember to open Google', after: 'A WhatsApp alert, right away, with the reply already written' }, { before: 'Days or weeks to reply to a comment', after: 'Reply published in seconds, from your WhatsApp' }, { before: "Opening Google's dashboard on a computer", after: 'Alert and approval with one tap, on your phone' }, { before: 'An unhappy customer only has Google to talk to', after: 'A direct channel to your team through the QR code, before it becomes a review' }, { before: 'You never know if a review turned into a pattern', after: "Binno points out what changed, with the customer's own words as proof" }] },
    honest: { eyebrow: 'The rule that never changes', title: 'Binno never hides a bad review.', body: "Some tools send happy customers to Google and unhappy ones to a private form. That's called review gating, and Google's policy bans it. Whoever gets caught can see reviews removed, their profile restricted, and a public notice on their listing saying fake reviews were found.", note: 'On Binno, the path to Google always shows up, whatever the rating. Automated checks in the code make sure that never changes.', link: "Read Google's review policy", linkHref: 'https://support.google.com/contributionpolicy/answer/7400114', rules: [{ ok: true, title: 'A 5-star customer', body: 'Sees the button to review on Google.' }, { ok: true, title: 'A 1-star customer', body: 'Sees the same button to review on Google. And can also, if they want, send you a private comment.' }, { ok: false, title: 'Asking "was it good?" before showing Google', body: "Doesn't exist on Binno. That's what Google calls review gating." }] },
    faq: { eyebrow: 'Frequently asked questions', title: 'What every owner asks before subscribing.', items: [{ question: 'How does the direct message keep negative comments off Google?', answer: "It doesn't stop anyone from leaving a review, and Binno never hides the path to Google. What it does is give you the chance to find out first. By scanning the QR code, the customer can send a private message to your team; if something went wrong, you fix it while they're still around." }, { question: 'Does Binno guarantee my Google rating will go up?', answer: 'No. The rating depends on what your customer actually experienced, and no honest tool promises to change that. What Binno guarantees is reply speed and a direct channel so fixable frustrations reach you before they reach Google.' }, { question: 'Do I need to install an app?', answer: 'No. After connecting your Google Business Profile to Binno (once, from your phone or computer), replying to reviews happens entirely on WhatsApp: you get the alert, read the ready-made reply and approve with one tap.' }, { question: 'Do I need to create an account before subscribing?', answer: 'No. You pay first and set up your access afterward, on the next screen. No form in the middle.' }, { question: 'Does the R$ {promo}/month price change later?', answer: 'Not for you. Subscribe in the founding batch and your R$ {promo} stays locked in even after the price goes back to R$ {regular}.' }] },
    finalCta: { eyebrow: 'Your next review lands today', title: 'Will you reply in seconds, or in weeks?', body: 'A WhatsApp alert, a reply already written, publishing with one tap. And a direct channel for the customer to talk to you before they talk to Google.', cta: 'Get Binno for R$ {promo}/month', micro: 'No form before you pay · Cancel anytime · No lock-in contract' },
    footer: { body: 'Reputation advice for local businesses.', demo: 'Demo', terms: 'Terms', privacy: 'Privacy' },
    contacto: { rotulo: 'Chat on WhatsApp', rotuloCurto: 'Talk to Binno', mensagemDaVenda: 'Hi! I came from the Binno site and would like to understand how it works.', mensagemDoNegocio: 'Hi! I saw Binno on a review page and would like to know how it works for my business.' },
  },
};

export const getMarketingCopy = (locale: Locale): MarketingCopy => COPY[locale] ?? COPY.en;
