import type { Locale } from '@/i18n';

export type MarketingCopy = {
  locale: Locale;
  nav: { howItWorks: string; capabilities: string; price: string; demo: string; login: string; start: string };
  hero: { eyebrow: string; title: string; body: string; primary: string; secondary: string; trust: string };
  maps: { eyebrow: string; title: string; body: string; note: string; link: string; steps: Array<{ title: string; body: string }> };
  alerts: { eyebrow: string; title: string; body: string; items: Array<{ title: string; body: string }> };
  /** A regra do review gating: nunca escondida, nunca ausente da home. */
  honest: { eyebrow: string; title: string; body: string; note: string; link: string };
  whatsapp: { eyebrow: string; title: string; body: string; items: string[]; note: string };
  replies: { eyebrow: string; title: string; body: string; note: string; link: string };
  history: { eyebrow: string; title: string; body: string; items: string[] };
  radar: { eyebrow: string; title: string; body: string; strengthTitle: string; strengthBody: string; riskTitle: string; riskBody: string };
  profile: { eyebrow: string; title: string; body: string; items: string[] };
  demo: { eyebrow: string; title: string; body: string; primary: string; label: string };
  /**
   * `promoLabel`, `regularLabel` e `promoNote` existem para o lote promocional
   * de fundadores. `promoNote` usa `{vagas}`, substituído por `comVagas`.
   */
  pricing: { eyebrow: string; title: string; body: string; cta: string; monthly: string; availableLabel: string; availableHint: string; promoLabel: string; regularLabel: string; promoNote: string };
  footer: { body: string; demo: string; terms: string; privacy: string };
  /**
   * O contacto directo, pedido por Marcelo em 02/09/2026 para começar a
   * prospecção. `mensagemDaVenda` já vai escrita na conversa e diz de onde a
   * pessoa veio; `mensagemDoNegocio` diz o mesmo a partir da página do QR.
   */
  contacto: { rotulo: string; rotuloCurto: string; mensagemDaVenda: string; mensagemDoNegocio: string };
  cockpit: {
    business: string; overview: string; reviews: string; whatsapp: string; illustration: string;
    radar: string; radarTitle: string; radarBody: string; queue: string; waiting: string; replySuggested: string;
    useReply: string; copied: string; edit: string; skip: string; openReview: string; reviewMessage: string;
    strength: string; fragility: string; volume: string; volumeBody: string; volumeAlert: string;
    stars: string; starsBody: string; qr: string; topics: string; reputation: string; responseTime: string;
    newReviews: string; plan: string; practice: string; completeness: string; weekly: string;
    whatsappTitle: string; whatsappBody: string; preferenceTitle: string; recipient: string; frequency: string;
    weeklySummary: string; radarAlerts: string; replyAlerts: string; profileAlerts: string; preview: string;
    previewBody: string; saved: string; details: string; sampleReviewer: string; replyExample: string; onePriority: string;
  };
};

const COPY: Record<Locale, MarketingCopy> = {
  'pt-BR': {
    locale: 'pt-BR',
    nav: { howItWorks: 'Como funciona', capabilities: 'O que ele acompanha', price: 'Plano', demo: 'Demonstração', login: 'Entrar', start: 'Começar' },
    hero: { eyebrow: 'BINNO PARA NEGÓCIOS LOCAIS', title: 'Seu assessor de reputação no Google. Você fica sabendo no mesmo dia, não três dias depois.', body: 'Cliente insatisfeito quase nunca reclama na hora. Vai embora calado e escreve depois, quando a avaliação já é pública e não tem mais o que fazer. O Binno te avisa enquanto ainda dá tempo.', primary: 'Começar agora', secondary: 'Ver o Binno em ação', trust: 'Você lê cada resposta e decide o que publicar. O Binno nunca publica sozinho.' },
    maps: { eyebrow: 'ANTES DE VOCÊ, ELE JÁ DECIDIU', title: '96% dos brasileiros leem avaliação no Google antes de escolher uma loja física.', body: 'Quem decide não é você. Não é o produto, não é o preço na porta. É a nota que aparece antes de a pessoa te conhecer. Quase 9 em cada 10 descartam quem tem menos de 4 estrelas — sem ligar, sem entrar, sem dar chance.', note: 'Fonte: pesquisa Decisão Local 2025 (Reclame Aqui e Harmo, 1.591 pessoas, 2025, mercado brasileiro). Informações completas ajudam o Google a entender melhor o negócio, e avaliações positivas podem contribuir para a presença local, sem garantia de posição ou de resultado.', link: 'Ler a orientação oficial do Google', steps: [{ title: 'A pesquisa', body: '96% leem avaliação antes de escolher onde ir.' }, { title: 'A nota', body: 'Abaixo de 4 estrelas, quase 9 em cada 10 já descartam.' }, { title: 'O Binno', body: 'Cuida da nota antes que ela custe cliente.' }] },
    alerts: { eyebrow: 'MONITORAMENTO', title: 'Não seja pego de surpresa.', body: 'Quando alguma coisa muda no seu Google, o Binno explica o que mudou e o que dá pra fazer agora. Uma coisa por vez.', items: [{ title: 'Queda fora do padrão', body: 'Quando o número de avaliações cai ou a mistura de notas muda de repente.' }, { title: 'Nota baixa ganhando espaço', body: 'Quando as de uma e duas estrelas começam a pesar mais do que pesavam.' }, { title: 'A mesma reclamação de novo', body: 'Quando três pessoas citam a mesma coisa, o problema não é o cliente. É o processo.' }] },
    honest: { eyebrow: 'A REGRA QUE NÃO MUDA', title: 'O Binno nunca esconde uma avaliação ruim.', body: 'Tem ferramenta que manda o cliente satisfeito pro Google e o insatisfeito pra um formulário privado. Isso chama-se review gating, e o Google pune desde abril de 2026. A punição não é perder posição: é apagar todas as avaliações do seu perfil e colocar um aviso vermelho na sua ficha.', note: 'No Binno o caminho pro Google aparece sempre, qualquer que seja a nota. São 23 verificações automáticas que quebram o sistema se alguém tentar mudar isso.', link: 'Ler a política de avaliações do Google' },
    whatsapp: { eyebrow: 'SEM MAIS UMA TELA PRA OLHAR', title: 'Você não precisa ter tempo para usar o Binno.', body: 'O Binno te procura no WhatsApp quando tem alguma coisa pra decidir. Você não precisa entrar em painel nenhum.', items: ['O que está te ajudando', 'O que está te atrapalhando', 'Avaliações esperando resposta', 'Uma coisa pra fazer essa semana'], note: 'Você escolhe quais avisos recebe, com que frequência, e em qual número.' },
    replies: { eyebrow: 'FILA DE RESPOSTAS', title: 'Responda suas avaliações do Google em 1 clique, direto do painel.', body: 'O rascunho já vem escrito, no idioma do cliente, assim que você abre. Ajusta se quiser, e publica sem sair do Binno.', note: 'Você decide o que vai pro Google. Publicar é um clique seu — o Binno nunca publica sozinho.', link: 'Conhecer as boas práticas do Google' },
    history: { eyebrow: 'LEITURA DA REPUTAÇÃO', title: 'Uma nota boa não significa que tudo está bem.', body: 'A média esconde a direção. O Binno mostra a história por trás dela — se você está ficando mais forte ou mais frágil.', items: ['Quantas avaliações chegaram, semana a semana', 'Cada nota separada, de uma a cinco estrelas', 'Como está agora comparado com antes', 'Os assuntos mais citados, e o que mudou na semana'] },
    radar: { eyebrow: 'RADAR DO BINNO', title: 'O que proteger, e o que mudar.', body: 'O Binno separa o elogio que se repete do problema que se repete. Cada um com a frase do cliente que provou aquilo, e uma coisa pra fazer.', strengthTitle: 'O que está te ajudando', strengthBody: 'O elogio que aparece de novo e de novo. É isso que merece foto, post e lugar de destaque.', riskTitle: 'O que está te atrapalhando', riskBody: 'A reclamação que se repete. Quase sempre é processo, não é pessoa.' },
    profile: { eyebrow: 'PLANO DO PERFIL', title: 'Uma coisa por vez pra arrumar no perfil.', body: 'O Binno não te dá lista de tarefa. Ele te dá a próxima.', items: ['Responder as avaliações que importam', 'Subir foto nova e atualizar informação', 'Conferir horário e dados do negócio', 'Ver quantas pessoas abriram o QR e foram pro Google'] },
    demo: { eyebrow: 'DEMONSTRAÇÃO', title: 'Veja o Binno funcionando antes de criar conta.', body: 'Um exemplo completo: o aviso, o Radar, a fila de respostas, o histórico e o WhatsApp.', primary: 'Explorar demonstração', label: 'Exemplo ilustrativo' },
    pricing: { eyebrow: 'PLANO BINNO', title: 'Lote de fundadores: 50 vagas a R$99 por mês.', body: 'Contratar alguém só pra cuidar disso custa, no mínimo, R$500 por mês. Quanto te custou o cliente que nem ligou, porque viu a nota antes de te conhecer? Depois que as vagas fecharem, o preço passa a R$199 pra quem entrar.', cta: 'Garantir minha vaga no lote', monthly: '/mês', availableLabel: 'Para negócios no Brasil', availableHint: 'O país onde o negócio opera é confirmado no cadastro e validado no pagamento.', promoLabel: 'LOTE DE FUNDADORES', regularLabel: 'De', promoNote: 'As primeiras {vagas} assinaturas ficam em R$99 por mês enquanto a assinatura seguir ativa. Quando o lote fechar, o preço volta a R$199 para quem assinar depois.' },
    footer: { body: 'Assessoria de reputação para negócios locais.', demo: 'Demonstração', terms: 'Termos', privacy: 'Privacidade' },
    contacto: { rotulo: 'Falar no WhatsApp', rotuloCurto: 'Falar com o Binno', mensagemDaVenda: 'Olá! Vim pelo site do Binno e queria entender melhor como funciona.', mensagemDoNegocio: 'Olá! Vi o Binno numa página de avaliação e queria saber como funciona para o meu negócio.' },
    cockpit: { business: 'Bistrô Horizonte', overview: 'Visão geral', reviews: 'Avaliações', whatsapp: 'WhatsApp', illustration: 'Demonstração ilustrativa', radar: 'Radar do Binno', radarTitle: 'Tempo de espera pede atenção', radarBody: 'Três avaliações recentes citam demora no atendimento. Revise a escala do horário de almoço antes da próxima semana.', queue: 'Fila de respostas', waiting: '3 avaliações esperam sua resposta', replySuggested: 'Resposta sugerida', useReply: 'Usar resposta', copied: 'Resposta pronta para colar', edit: 'Editar', skip: 'Pular', openReview: 'Abrir avaliação no Google', reviewMessage: 'O atendimento demorou mais do que o esperado e ninguém explicou o que estava acontecendo.', strength: 'O que está ajudando', fragility: 'O que está fragilizando', volume: 'Volume de avaliações', volumeBody: '3 avaliações nesta semana, média de 10', volumeAlert: 'Queda de 70% em relação à média das últimas oito semanas.', stars: 'Cada nota separada', starsBody: 'Cinco estrelas perderam força. Notas uma e duas cresceram no período.', qr: 'Do QR ao Google', topics: 'Temas mais citados', reputation: 'Reputação no Google', responseTime: 'Tempo médio de resposta', newReviews: 'Novas avaliações em 30 dias', plan: 'Plano de hoje', practice: 'Reforce fotos do prato executivo. Ele aparece entre os elogios recentes.', completeness: 'Completude do perfil', weekly: 'O que mudou na semana', whatsappTitle: 'Resumo no WhatsApp', whatsappBody: 'O Binno entrega o essencial para você não precisar procurar informação.', preferenceTitle: 'Escolha o que quer receber', recipient: 'WhatsApp do gestor', frequency: 'Frequência', weeklySummary: 'Resumo semanal', radarAlerts: 'Alertas do Radar', replyAlerts: 'Avaliações que pedem resposta', profileAlerts: 'Melhorias do Perfil do Google', preview: 'Prévia da mensagem', previewBody: 'Esta semana: o atendimento segue como força. Tempo de espera apareceu em três avaliações. Revise a fila de respostas e a escala do almoço.', saved: 'Preferências salvas nesta demonstração.', details: 'Ver detalhes', sampleReviewer: 'Mariana Souza', replyExample: 'Mariana, sentimos muito pela sua experiência. Já estamos revisando a organização do atendimento nos horários mais movimentados. Obrigado por nos contar o que aconteceu.', onePriority: 'Uma prioridade útil por vez' },
  },
  'pt-PT': {
    locale: 'pt-PT',
    nav: { howItWorks: 'Como funciona', capabilities: 'O que acompanha', price: 'Plano', demo: 'Demonstração', login: 'Entrar', start: 'Começar' },
    hero: { eyebrow: 'BINNO PARA NEGÓCIOS LOCAIS', title: 'O seu assessor de reputação no Google. Fica a saber no mesmo dia, não três dias depois.', body: 'Cliente insatisfeito quase nunca reclama na hora. Vai-se embora calado e escreve depois, quando a avaliação já é pública e já não há nada a fazer. O Binno avisa-o enquanto ainda há tempo.', primary: 'Começar agora', secondary: 'Ver o Binno em ação', trust: 'Revê cada resposta e decide o que publicar. O Binno nunca publica sozinho.' },
    maps: { eyebrow: 'ANTES DE SI, ELE JÁ DECIDIU', title: '96% dos brasileiros leem avaliações no Google antes de escolher uma loja física.', body: 'Quem decide não é o dono. Não é o produto, não é o preço à porta. É a nota que aparece antes de a pessoa o conhecer. Quase 9 em cada 10 descartam quem tem menos de 4 estrelas — sem ligar, sem entrar, sem dar hipótese.', note: 'Fonte: estudo Decisão Local 2025 (Reclame Aqui e Harmo, 1.591 pessoas, 2025, mercado brasileiro). Informações completas ajudam o Google a compreender melhor o negócio, e avaliações positivas podem contribuir para a presença local, sem garantia de posição ou de resultado.', link: 'Ler a orientação oficial do Google', steps: [{ title: 'A pesquisa', body: '96% leem avaliações antes de escolher onde ir.' }, { title: 'A nota', body: 'Abaixo de 4 estrelas, quase 9 em cada 10 já descartam.' }, { title: 'O Binno', body: 'Cuida da nota antes que ela custe um cliente.' }] },
    alerts: { eyebrow: 'MONITORIZAÇÃO', title: 'Não seja apanhado de surpresa.', body: 'Quando alguma coisa muda no seu Google, o Binno explica o que mudou e o que pode fazer agora. Uma coisa de cada vez.', items: [{ title: 'Queda fora do padrão', body: 'Quando o número de avaliações cai ou a mistura de classificações muda de repente.' }, { title: 'Classificação baixa a ganhar espaço', body: 'Quando as de uma e duas estrelas começam a pesar mais do que pesavam.' }, { title: 'A mesma reclamação outra vez', body: 'Quando três pessoas referem a mesma coisa, o problema não é o cliente. É o processo.' }] },
    honest: { eyebrow: 'A REGRA QUE NÃO MUDA', title: 'O Binno nunca esconde uma avaliação má.', body: 'Há ferramentas que mandam o cliente satisfeito para o Google e o insatisfeito para um formulário privado. Chama-se review gating, e o Google pune desde abril de 2026. A punição não é perder posição: é apagar todas as avaliações do perfil e colocar um aviso vermelho na ficha.', note: 'No Binno o caminho para o Google aparece sempre, seja qual for a nota. São 23 verificações automáticas que quebram o sistema se alguém tentar mudar isso.', link: 'Ler a política de avaliações do Google' },
    whatsapp: { eyebrow: 'SEM MAIS UM ECRÃ PARA OLHAR', title: 'Não precisa de ter tempo para usar o Binno.', body: 'O Binno procura-o no WhatsApp quando há algo para decidir. Não precisa de entrar em painel nenhum.', items: ['O que o está a ajudar', 'O que o está a atrapalhar', 'Avaliações à espera de resposta', 'Uma coisa para fazer esta semana'], note: 'Escolhe que avisos recebe, com que frequência, e em que número.' },
    replies: { eyebrow: 'FILA DE RESPOSTAS', title: 'Responda às suas avaliações do Google num clique, direto do painel.', body: 'O rascunho já vem escrito, na língua do cliente, assim que abre. Ajusta se quiser, e publica sem sair do Binno.', note: 'Decide o que vai para o Google. Publicar é um clique seu — o Binno nunca publica sozinho.', link: 'Conhecer as boas práticas do Google' },
    history: { eyebrow: 'LEITURA DA REPUTAÇÃO', title: 'Uma nota boa não significa que está tudo bem.', body: 'A média esconde a direção. O Binno mostra a história por trás dela — se está a ficar mais forte ou mais frágil.', items: ['Quantas avaliações chegaram, semana a semana', 'Cada nota separada, de uma a cinco estrelas', 'Como está agora comparado com antes', 'Os assuntos mais citados, e o que mudou na semana'] },
    radar: { eyebrow: 'RADAR DO BINNO', title: 'O que proteger, e o que mudar.', body: 'O Binno separa o elogio que se repete do problema que se repete. Cada um com a frase do cliente que o provou, e uma coisa a fazer.', strengthTitle: 'O que o está a ajudar', strengthBody: 'O elogio que aparece vezes sem conta. É isso que merece foto, publicação e lugar de destaque.', riskTitle: 'O que o está a atrapalhar', riskBody: 'A reclamação que se repete. Quase sempre é processo, não é pessoa.' },
    profile: { eyebrow: 'PLANO DO PERFIL', title: 'Uma coisa de cada vez para arrumar no perfil.', body: 'O Binno não lhe dá uma lista de tarefas. Dá-lhe a próxima.', items: ['Responder às avaliações que importam', 'Publicar foto nova e atualizar informação', 'Conferir horário e dados do negócio', 'Ver quantas pessoas abriram o QR e foram para o Google'] },
    demo: { eyebrow: 'DEMONSTRAÇÃO', title: 'Veja o Binno a funcionar antes de criar conta.', body: 'Um exemplo completo: o aviso, o Radar, a fila de respostas, o histórico e o WhatsApp.', primary: 'Explorar demonstração', label: 'Exemplo ilustrativo' },
    pricing: { eyebrow: 'PLANO BINNO', title: 'Lote de fundadores: 50 vagas a R$99 por mês.', body: 'Contratar alguém só para cuidar disto custa, no mínimo, R$500 por mês. Quanto lhe custou o cliente que nem ligou, porque viu a nota antes de o conhecer? Depois que as vagas fecharem, o preço passa a R$199 para quem entrar.', cta: 'Garantir a minha vaga no lote', monthly: '/mês', availableLabel: 'Para negócios no Brasil', availableHint: 'O país onde o negócio opera é confirmado no cadastro e validado no pagamento.', promoLabel: 'LOTE DE FUNDADORES', regularLabel: 'De', promoNote: 'As primeiras {vagas} subscrições ficam em R$99 por mês enquanto a subscrição continuar ativa. Quando o lote fechar, o preço volta a R$199 para quem subscrever depois.' },
    footer: { body: 'Assessoria de reputação para negócios locais.', demo: 'Demonstração', terms: 'Termos', privacy: 'Privacidade' },
    contacto: { rotulo: 'Falar no WhatsApp', rotuloCurto: 'Falar com o Binno', mensagemDaVenda: 'Olá! Vim pelo site do Binno e queria perceber melhor como funciona.', mensagemDoNegocio: 'Olá! Vi o Binno numa página de avaliação e queria saber como funciona para o meu negócio.' },
    cockpit: { business: 'Bistrô Horizonte', overview: 'Visão geral', reviews: 'Avaliações', whatsapp: 'WhatsApp', illustration: 'Demonstração ilustrativa', radar: 'Radar do Binno', radarTitle: 'Tempo de espera pede atenção', radarBody: 'Três avaliações recentes referem demora no atendimento. Reveja a escala do almoço antes da próxima semana.', queue: 'Fila de respostas', waiting: '3 avaliações aguardam resposta', replySuggested: 'Resposta sugerida', useReply: 'Usar resposta', copied: 'Resposta pronta a colar', edit: 'Editar', skip: 'Saltar', openReview: 'Abrir avaliação no Google', reviewMessage: 'O atendimento demorou mais do que o esperado e ninguém explicou o que estava a acontecer.', strength: 'O que está a ajudar', fragility: 'O que está a fragilizar', volume: 'Volume de avaliações', volumeBody: '3 avaliações esta semana, média de 10', volumeAlert: 'Queda de 70% em relação à média das últimas oito semanas.', stars: 'Cada nota separada', starsBody: 'Cinco estrelas perderam força. Notas uma e duas cresceram no período.', qr: 'Do QR ao Google', topics: 'Temas mais citados', reputation: 'Reputação no Google', responseTime: 'Tempo médio de resposta', newReviews: 'Novas avaliações em 30 dias', plan: 'Plano de hoje', practice: 'Reforce fotografias do prato executivo. Surge entre os elogios recentes.', completeness: 'Completude do perfil', weekly: 'O que mudou na semana', whatsappTitle: 'Resumo no WhatsApp', whatsappBody: 'O Binno entrega o essencial para não precisar de procurar informação.', preferenceTitle: 'Escolha o que quer receber', recipient: 'WhatsApp do gestor', frequency: 'Frequência', weeklySummary: 'Resumo semanal', radarAlerts: 'Alertas do Radar', replyAlerts: 'Avaliações que pedem resposta', profileAlerts: 'Melhorias do Perfil do Google', preview: 'Pré-visualização da mensagem', previewBody: 'Esta semana: o atendimento continua a ser uma força. Tempo de espera surgiu em três avaliações. Reveja a fila de respostas e a escala do almoço.', saved: 'Preferências guardadas nesta demonstração.', details: 'Ver detalhes', sampleReviewer: 'Mariana Souza', replyExample: 'Mariana, lamentamos muito a sua experiência. Já estamos a rever a organização do atendimento nos horários mais movimentados. Obrigado por nos contar o que aconteceu.', onePriority: 'Uma prioridade útil de cada vez' },
  },
  en: {
    locale: 'en',
    nav: { howItWorks: 'How it works', capabilities: 'What it tracks', price: 'Plan', demo: 'Demo', login: 'Log in', start: 'Get started' },
    hero: { eyebrow: 'BINNO FOR LOCAL BUSINESSES', title: 'Your reputation advisor on Google. You find out the same day, not three days later.', body: 'An unhappy customer almost never complains on the spot. They leave quietly and write about it later, once the review is already public and there is nothing left to do. Binno tells you while there is still time.', primary: 'Get started', secondary: 'See Binno in action', trust: 'You read every reply and decide what to publish. Binno never publishes on its own.' },
    maps: { eyebrow: 'BEFORE YOU, THEY ALREADY DECIDED', title: '96% of Brazilian consumers read Google reviews before choosing a physical store.', body: 'It is not you who decides. Not the product, not the price on the door. It is the rating that shows up before the person knows you. Nearly 9 in 10 rule out a business with under 4 stars — without calling, without visiting, without giving it a chance.', note: 'Source: Decisão Local 2025 study (Reclame Aqui and Harmo, 1,591 people, 2025, Brazilian market). Complete information helps Google understand a business, and positive reviews can contribute to local presence, with no guarantee of position or outcome.', link: 'Read Google guidance', steps: [{ title: 'The search', body: '96% read reviews before choosing where to go.' }, { title: 'The rating', body: 'Under 4 stars, nearly 9 in 10 already rule you out.' }, { title: 'Binno', body: 'Takes care of your rating before it costs you a customer.' }] },
    alerts: { eyebrow: 'MONITORING', title: 'Do not be caught by surprise.', body: 'When something changes on your Google profile, Binno explains what changed and what you can do about it now. One thing at a time.', items: [{ title: 'An unusual decline', body: 'When the number of reviews drops or the rating mix shifts suddenly.' }, { title: 'Low ratings gaining ground', body: 'When one and two star reviews start to carry more weight.' }, { title: 'The same complaint again', body: 'When three people mention the same thing, the problem is not the customer. It is the process.' }] },
    honest: { eyebrow: 'THE RULE THAT NEVER CHANGES', title: 'Binno never hides a bad review.', body: 'Some tools send happy customers to Google and unhappy ones to a private form. That is called review gating, and Google has penalized it since April 2026. The penalty is not losing ranking: it is deleting every review on your profile and adding a red warning to your listing.', note: 'On Binno, the path to Google always shows up, whatever the rating. 23 automated checks break the build if anyone tries to change that.', link: 'Read Google review policy' },
    whatsapp: { eyebrow: 'ADVICE WITHOUT ANOTHER SCREEN', title: 'You do not need time to use Binno.', body: 'Binno comes to you on WhatsApp when there is something to decide. You never need to open a dashboard.', items: ['What is helping you', 'What is hurting you', 'Reviews waiting for a reply', 'One thing to do this week'], note: 'You choose which alerts you get, how often, and on which number.' },
    replies: { eyebrow: 'REPLY QUEUE', title: 'Reply to your Google reviews in one click, right from the dashboard.', body: 'The draft is already written, in the customer\'s language, the moment you open it. Adjust it if you want, and publish without leaving Binno.', note: 'You decide what goes on Google. Publishing is your click — Binno never publishes on its own.', link: 'Read Google review guidance' },
    history: { eyebrow: 'REPUTATION READING', title: 'A good rating does not mean everything is fine.', body: 'The average hides the direction. Binno shows the story behind it — whether you are getting stronger or more vulnerable.', items: ['How many reviews came in, week by week', 'Each rating tracked separately, one to five stars', 'How it compares with before', 'The topics people mention most, and what changed this week'] },
    radar: { eyebrow: 'BINNO RADAR', title: 'What to protect, and what to change.', body: 'Binno separates the praise that keeps repeating from the problem that keeps repeating. Each one comes with the customer quote that proves it, and one thing to do.', strengthTitle: 'What is helping you', strengthBody: 'The praise that keeps showing up. That is what deserves a photo, a post, and a spotlight.', riskTitle: 'What is hurting you', riskBody: 'The complaint that keeps repeating. It is almost always a process, not a person.' },
    profile: { eyebrow: 'PROFILE PLAN', title: 'One thing at a time to fix on your profile.', body: 'Binno does not hand you a to-do list. It hands you the next thing.', items: ['Reply to the reviews that matter', 'Add a new photo and update information', 'Check hours and business details', 'See how many people opened the QR and went to Google'] },
    demo: { eyebrow: 'DEMO', title: 'See Binno working before you sign up.', body: 'A full example: the alert, the Radar, the reply queue, the history and WhatsApp.', primary: 'Explore the demo', label: 'Illustrative example' },
    pricing: { eyebrow: 'BINNO PLAN', title: 'Founding batch: 50 spots at R$99 a month.', body: 'Hiring someone just to handle this costs at least R$500 a month. What did it cost you, the customer who never called because they saw the rating before they knew you? Once the spots are gone, the price goes to R$199 for anyone who joins after.', cta: 'Claim my spot in the batch', monthly: '/month', availableLabel: 'For businesses in Brazil', availableHint: 'We confirm where the business operates during sign-up and validate it at payment.', promoLabel: 'FOUNDING BATCH', regularLabel: 'From', promoNote: 'The first {vagas} subscriptions stay at R$99 per month for as long as the subscription remains active. Once the batch closes, the price returns to R$199 for anyone who subscribes later.' },
    footer: { body: 'Reputation advice for local businesses.', demo: 'Demo', terms: 'Terms', privacy: 'Privacy' },
    contacto: { rotulo: 'Chat on WhatsApp', rotuloCurto: 'Talk to Binno', mensagemDaVenda: 'Hi! I came from the Binno site and would like to understand how it works.', mensagemDoNegocio: 'Hi! I saw Binno on a review page and would like to know how it works for my business.' },
    cockpit: { business: 'Horizon Bistro', overview: 'Overview', reviews: 'Reviews', whatsapp: 'WhatsApp', illustration: 'Illustrative demo', radar: 'Binno Radar', radarTitle: 'Waiting time needs attention', radarBody: 'Three recent reviews mention slow service. Review the lunch shift before next week.', queue: 'Reply queue', waiting: '3 reviews are waiting for your reply', replySuggested: 'Suggested reply', useReply: 'Use reply', copied: 'Reply ready to paste', edit: 'Edit', skip: 'Skip', openReview: 'Open review on Google', reviewMessage: 'Service took longer than expected and nobody explained what was happening.', strength: 'What is helping', fragility: 'What is making you vulnerable', volume: 'Review volume', volumeBody: '3 reviews this week, average of 10', volumeAlert: 'A 70% drop compared with the previous eight week average.', stars: 'Each rating separately', starsBody: 'Five star reviews lost share. One and two star ratings grew in this period.', qr: 'From QR to Google', topics: 'Most cited themes', reputation: 'Google reputation', responseTime: 'Average reply time', newReviews: 'New reviews in 30 days', plan: 'Today\'s plan', practice: 'Add a recent photo of the executive lunch. It appears in recent praise.', completeness: 'Profile completeness', weekly: 'What changed this week', whatsappTitle: 'WhatsApp summary', whatsappBody: 'Binno delivers the essentials so you do not have to look for information.', preferenceTitle: 'Choose what you want to receive', recipient: 'Manager WhatsApp', frequency: 'Frequency', weeklySummary: 'Weekly summary', radarAlerts: 'Radar alerts', replyAlerts: 'Reviews needing a reply', profileAlerts: 'Business Profile improvements', preview: 'Message preview', previewBody: 'This week: service remains a strength. Waiting time appeared in three reviews. Review the reply queue and lunch shift.', saved: 'Preferences saved in this demo.', details: 'View details', sampleReviewer: 'Mariana Souza', replyExample: 'Mariana, we are very sorry about your experience. We are reviewing service organization during the busiest hours. Thank you for telling us what happened.', onePriority: 'One useful priority at a time' },
  },
};

export const getMarketingCopy = (locale: Locale): MarketingCopy => COPY[locale] ?? COPY.en;
