import type { Locale } from '@/i18n';

export type MarketingCopy = {
  locale: Locale;
  nav: { howItWorks: string; capabilities: string; price: string; demo: string; login: string; start: string };
  hero: { eyebrow: string; title: string; body: string; primary: string; secondary: string; trust: string };
  maps: { eyebrow: string; title: string; body: string; note: string; link: string; steps: Array<{ title: string; body: string }> };
  alerts: { eyebrow: string; title: string; body: string; items: Array<{ title: string; body: string }> };
  whatsapp: { eyebrow: string; title: string; body: string; items: string[]; note: string };
  replies: { eyebrow: string; title: string; body: string; note: string; link: string };
  history: { eyebrow: string; title: string; body: string; items: string[] };
  radar: { eyebrow: string; title: string; body: string; strengthTitle: string; strengthBody: string; riskTitle: string; riskBody: string };
  profile: { eyebrow: string; title: string; body: string; items: string[] };
  demo: { eyebrow: string; title: string; body: string; primary: string; label: string };
  /**
   * `promoLabel` e `promoNote` existem para o lote promocional de fundadores.
   * `promoNote` usa `{vagas}`, substituído por `comVagas`.
   *
   * Não escrever preço dentro destes textos. Os números saem de
   * `precoBinno.ts` e são renderizados ao lado; já houve uma versão no ar que
   * dizia "De R$199 por R$199" porque o rótulo repetia o que o componente já
   * mostrava. A única exceção é o preço cheio citado no fim do `promoNote`,
   * que fala do depois do lote e não tem número renderizado por perto.
   */
  pricing: { eyebrow: string; title: string; body: string; cta: string; monthly: string; availableLabel: string; availableHint: string; promoLabel: string; promoNote: string };
  footer: { body: string; demo: string; terms: string; privacy: string };
  /**
   * O contacto directo, pedido por Marcelo em 02/09/2026 para começar a
   * prospecção. `mensagemDaVenda` já vai escrita na conversa e diz de onde a
   * pessoa veio; `mensagemDoNegocio` diz o mesmo a partir da página do QR.
   */
  contacto: { rotulo: string; rotuloCurto: string; mensagemDaVenda: string; mensagemDoNegocio: string };
  cockpit: {
    business: string; overview: string; reviews: string; whatsapp: string; illustration: string;
    radar: string; radarTitle: string; radarBody: string; queue: string; waiting: string; replySuggested: string;
    useReply: string; copied: string; edit: string; skip: string; openReview: string; reviewMessage: string;
    strength: string; fragility: string; volume: string; volumeBody: string; volumeAlert: string;
    stars: string; starsBody: string; qr: string; topics: string; reputation: string; responseTime: string;
    newReviews: string; plan: string; practice: string; completeness: string; weekly: string;
    whatsappTitle: string; whatsappBody: string; preferenceTitle: string; recipient: string; frequency: string;
    weeklySummary: string; radarAlerts: string; replyAlerts: string; profileAlerts: string; preview: string;
    previewBody: string; saved: string; details: string; sampleReviewer: string; replyExample: string; onePriority: string;
  };
};

const COPY: Record<Locale, MarketingCopy> = {
  'pt-BR': {
    locale: 'pt-BR',
    nav: { howItWorks: 'Como o Binno assessora', capabilities: 'O que ele acompanha', price: 'Plano', demo: 'Demonstração', login: 'Entrar', start: 'Começar' },
    hero: { eyebrow: 'BINNO PARA NEGÓCIOS LOCAIS', title: 'Seu assessor de reputação no Google.', body: 'O Binno acompanha suas avaliações, identifica mudanças importantes e mostra o que fazer para proteger e fortalecer a percepção do seu negócio.', primary: 'Começar agora', secondary: 'Ver o Binno em ação', trust: 'Você revisa cada resposta e decide o que publicar.' },
    maps: { eyebrow: 'QUANDO O GOOGLE MAPS É UMA PORTA DE ENTRADA', title: 'Seu negócio é encontrado no Google. Sua reputação ajuda clientes a escolher.', body: 'O Binno organiza avaliações, informações do perfil e sinais que afetam a experiência de quem encontra você no Maps.', note: 'Informações completas ajudam o Google a entender melhor o negócio. Avaliações e notas positivas podem contribuir para a presença local, sem garantia de posição ou resultado.', link: 'Ler orientação oficial do Google', steps: [{ title: 'Google Maps', body: 'O cliente encontra, compara e decide.' }, { title: 'Reputação', body: 'Avaliações ajudam a formar essa decisão.' }, { title: 'Binno', body: 'O assessor mostra o que fazer agora.' }] },
    alerts: { eyebrow: 'MONITORAMENTO', title: 'Não seja pego de surpresa.', body: 'Quando o Binno identifica uma mudança que merece atenção, ele explica o sinal e indica a próxima ação útil.', items: [{ title: 'Queda fora do padrão', body: 'Veja quando o volume ou a composição das notas muda de forma relevante.' }, { title: 'Notas baixas em crescimento', body: 'Entenda se avaliações de uma ou duas estrelas começam a ganhar espaço.' }, { title: 'Tema negativo recorrente', body: 'Conecte comentários a um problema operacional antes que ele se repita.' }] },
    whatsapp: { eyebrow: 'ASSESSORIA SEM MAIS UMA TELA', title: 'Você não precisa ter tempo para usar o Binno.', body: 'O Binno vai até você no WhatsApp quando houver algo útil para decidir e entrega um resumo semanal quando você precisar de contexto.', items: ['O que fortaleceu sua reputação', 'O que deixou o negócio mais vulnerável', 'Avaliações que exigem atenção', 'Uma oportunidade prática para agir'], note: 'Você escolhe os avisos, a frequência e o número que recebe o acompanhamento.' },
    replies: { eyebrow: 'FILA ASSISTIDA', title: 'Responda clientes sem parar para pensar no que dizer.', body: 'O Binno lê o comentário, sugere uma resposta no idioma da avaliação e prepara o caminho até o review certo no Google.', note: 'Você revisa, ajusta se quiser e publica. O Binno não publica respostas sozinho.', link: 'Conhecer as boas práticas do Google' },
    history: { eyebrow: 'LEITURA DA REPUTAÇÃO', title: 'Uma nota boa não significa que tudo está bem.', body: 'Acompanhe a história por trás da média para entender se a reputação está mais forte ou mais vulnerável.', items: ['Volume de avaliações por período', 'Evolução separada de uma a cinco estrelas', 'Comparação com períodos anteriores', 'Temas mais citados e mudança semanal'] },
    radar: { eyebrow: 'RADAR DO BINNO', title: 'Transforme avaliações em decisões para o negócio.', body: 'O assessor separa o que merece ser protegido do que precisa mudar, sempre com uma evidência e uma ação possível.', strengthTitle: 'O que está ajudando', strengthBody: 'Identifique elogios recorrentes, produtos e aspectos que podem ganhar mais espaço.', riskTitle: 'O que está fragilizando', riskBody: 'Localize reclamações recorrentes e aja sobre o processo que está afetando clientes.' },
    profile: { eyebrow: 'PLANO DO PERFIL', title: 'Mantenha o Perfil da Empresa em dia.', body: 'O Binno transforma boas práticas em uma prioridade útil por vez.', items: ['Responder avaliações importantes', 'Atualizar fotos e informações', 'Revisar horários e dados do negócio', 'Acompanhar QR aberto e clique para o Google'] },
    demo: { eyebrow: 'DEMONSTRAÇÃO COMPLETA', title: 'Veja como o Binno assessora um negócio na prática.', body: 'Explore um cenário ilustrativo completo: alerta, Radar, fila de respostas, histórico e preferências de WhatsApp.', primary: 'Explorar demonstração', label: 'Demonstração ilustrativa' },
    pricing: { eyebrow: 'PLANO BINNO', title: 'Assessoria de reputação para o dia a dia do seu negócio.', body: 'Uma leitura clara do Google, prioridades práticas e respostas mais fáceis de conduzir.', cta: 'Começar agora', monthly: '/mês', availableLabel: 'Para negócios no Brasil', availableHint: 'O país onde o negócio opera é confirmado no cadastro e validado no pagamento.', promoLabel: 'LOTE DE FUNDADORES', promoNote: 'As {vagas} primeiras assinaturas mantêm esse preço enquanto seguirem ativas. Depois, volta a R${regular}.' },
    footer: { body: 'Assessoria de reputação para negócios locais.', demo: 'Demonstração', terms: 'Termos', privacy: 'Privacidade' },
    contacto: { rotulo: 'Falar no WhatsApp', rotuloCurto: 'Falar com o Binno', mensagemDaVenda: 'Olá! Vim pelo site do Binno e queria entender melhor como funciona.', mensagemDoNegocio: 'Olá! Vi o Binno numa página de avaliação e queria saber como funciona para o meu negócio.' },
    cockpit: { business: 'Bistrô Horizonte', overview: 'Visão geral', reviews: 'Avaliações', whatsapp: 'WhatsApp', illustration: 'Demonstração ilustrativa', radar: 'Radar do Binno', radarTitle: 'Tempo de espera pede atenção', radarBody: 'Três avaliações recentes citam demora no atendimento. Revise a escala do horário de almoço antes da próxima semana.', queue: 'Fila de respostas', waiting: '3 avaliações esperam sua resposta', replySuggested: 'Resposta sugerida', useReply: 'Usar resposta', copied: 'Resposta pronta para colar', edit: 'Editar', skip: 'Pular', openReview: 'Abrir avaliação no Google', reviewMessage: 'O atendimento demorou mais do que o esperado e ninguém explicou o que estava acontecendo.', strength: 'O que está ajudando', fragility: 'O que está fragilizando', volume: 'Volume de avaliações', volumeBody: '3 avaliações nesta semana, média de 10', volumeAlert: 'Queda de 70% em relação à média das últimas oito semanas.', stars: 'Cada nota separada', starsBody: 'Cinco estrelas perderam força. Notas uma e duas cresceram no período.', qr: 'Do QR ao Google', topics: 'Temas mais citados', reputation: 'Reputação no Google', responseTime: 'Tempo médio de resposta', newReviews: 'Novas avaliações em 30 dias', plan: 'Plano de hoje', practice: 'Reforce fotos do prato executivo. Ele aparece entre os elogios recentes.', completeness: 'Completude do perfil', weekly: 'O que mudou na semana', whatsappTitle: 'Resumo no WhatsApp', whatsappBody: 'O Binno entrega o essencial para você não precisar procurar informação.', preferenceTitle: 'Escolha o que quer receber', recipient: 'WhatsApp do gestor', frequency: 'Frequência', weeklySummary: 'Resumo semanal', radarAlerts: 'Alertas do Radar', replyAlerts: 'Avaliações que pedem resposta', profileAlerts: 'Melhorias do Perfil do Google', preview: 'Prévia da mensagem', previewBody: 'Esta semana: o atendimento segue como força. Tempo de espera apareceu em três avaliações. Revise a fila de respostas e a escala do almoço.', saved: 'Preferências salvas nesta demonstração.', details: 'Ver detalhes', sampleReviewer: 'Mariana Souza', replyExample: 'Mariana, sentimos muito pela sua experiência. Já estamos revisando a organização do atendimento nos horários mais movimentados. Obrigado por nos contar o que aconteceu.', onePriority: 'Uma prioridade útil por vez' },
  },
  'pt-PT': {
    locale: 'pt-PT',
    nav: { howItWorks: 'Como o Binno assessora', capabilities: 'O que acompanha', price: 'Plano', demo: 'Demonstração', login: 'Entrar', start: 'Começar' },
    hero: { eyebrow: 'BINNO PARA NEGÓCIOS LOCAIS', title: 'O seu assessor de reputação no Google.', body: 'O Binno acompanha as suas avaliações, identifica mudanças importantes e mostra o que fazer para proteger e reforçar a perceção do seu negócio.', primary: 'Começar agora', secondary: 'Ver o Binno em ação', trust: 'Revê cada resposta e decide o que publicar.' },
    maps: { eyebrow: 'QUANDO O GOOGLE MAPS É UMA PORTA DE ENTRADA', title: 'O seu negócio é encontrado no Google. A sua reputação ajuda clientes a escolher.', body: 'O Binno organiza avaliações, informações do perfil e sinais que afetam a experiência de quem encontra o seu negócio no Maps.', note: 'Informações completas ajudam o Google a compreender melhor o negócio. Avaliações e classificações positivas podem contribuir para a presença local, sem garantia de posição ou resultado.', link: 'Ler orientação oficial do Google', steps: [{ title: 'Google Maps', body: 'O cliente encontra, compara e decide.' }, { title: 'Reputação', body: 'As avaliações ajudam a formar essa decisão.' }, { title: 'Binno', body: 'O assessor mostra o que fazer agora.' }] },
    alerts: { eyebrow: 'MONITORIZAÇÃO', title: 'Não seja apanhado de surpresa.', body: 'Quando o Binno identifica uma mudança que merece atenção, explica o sinal e indica a próxima ação útil.', items: [{ title: 'Queda fora do padrão', body: 'Veja quando o volume ou a composição das classificações muda de forma relevante.' }, { title: 'Classificações baixas a crescer', body: 'Entenda se avaliações de uma ou duas estrelas começam a ganhar espaço.' }, { title: 'Tema negativo recorrente', body: 'Ligue comentários a um problema operacional antes que se repita.' }] },
    whatsapp: { eyebrow: 'ASSESSORIA SEM MAIS UM ECRÃ', title: 'Não precisa de ter tempo para usar o Binno.', body: 'O Binno vai até si no WhatsApp quando houver algo útil para decidir e entrega um resumo semanal quando precisar de contexto.', items: ['O que reforçou a sua reputação', 'O que deixou o negócio mais vulnerável', 'Avaliações que exigem atenção', 'Uma oportunidade prática para agir'], note: 'Escolhe os avisos, a frequência e o número que recebe o acompanhamento.' },
    replies: { eyebrow: 'FILA ASSISTIDA', title: 'Responda a clientes sem parar para pensar no que dizer.', body: 'O Binno lê o comentário, sugere uma resposta no idioma da avaliação e prepara o caminho até à avaliação certa no Google.', note: 'Revê, ajusta se quiser e publica. O Binno não publica respostas sozinho.', link: 'Conhecer as boas práticas do Google' },
    history: { eyebrow: 'LEITURA DA REPUTAÇÃO', title: 'Uma nota boa não significa que está tudo bem.', body: 'Acompanhe a história por trás da média para entender se a reputação está mais forte ou mais vulnerável.', items: ['Volume de avaliações por período', 'Evolução separada de uma a cinco estrelas', 'Comparação com períodos anteriores', 'Temas mais citados e mudança semanal'] },
    radar: { eyebrow: 'RADAR DO BINNO', title: 'Transforme avaliações em decisões para o negócio.', body: 'O assessor separa o que merece ser protegido do que precisa de mudar, sempre com uma evidência e uma ação possível.', strengthTitle: 'O que está a ajudar', strengthBody: 'Identifique elogios recorrentes, produtos e aspetos que podem ganhar mais espaço.', riskTitle: 'O que está a fragilizar', riskBody: 'Localize reclamações recorrentes e aja sobre o processo que está a afetar clientes.' },
    profile: { eyebrow: 'PLANO DO PERFIL', title: 'Mantenha o Perfil da Empresa em dia.', body: 'O Binno transforma boas práticas numa prioridade útil de cada vez.', items: ['Responder a avaliações importantes', 'Atualizar fotografias e informações', 'Rever horários e dados do negócio', 'Acompanhar QR aberto e clique para o Google'] },
    demo: { eyebrow: 'DEMONSTRAÇÃO COMPLETA', title: 'Veja como o Binno assessora um negócio na prática.', body: 'Explore um cenário ilustrativo completo: alerta, Radar, fila de respostas, histórico e preferências de WhatsApp.', primary: 'Explorar demonstração', label: 'Demonstração ilustrativa' },
    pricing: { eyebrow: 'PLANO BINNO', title: 'Assessoria de reputação para o dia a dia do seu negócio.', body: 'Uma leitura clara do Google, prioridades práticas e respostas mais fáceis de conduzir.', cta: 'Começar agora', monthly: '/mês', availableLabel: 'Para negócios no Brasil', availableHint: 'O país onde o negócio opera é confirmado no cadastro e validado no pagamento.', promoLabel: 'LOTE DE FUNDADORES', promoNote: 'As {vagas} primeiras subscrições mantêm este preço enquanto se mantiverem ativas. Depois, volta a R${regular}.' },
    footer: { body: 'Assessoria de reputação para negócios locais.', demo: 'Demonstração', terms: 'Termos', privacy: 'Privacidade' },
    contacto: { rotulo: 'Falar no WhatsApp', rotuloCurto: 'Falar com o Binno', mensagemDaVenda: 'Olá! Vim pelo site do Binno e queria perceber melhor como funciona.', mensagemDoNegocio: 'Olá! Vi o Binno numa página de avaliação e queria saber como funciona para o meu negócio.' },
    cockpit: { business: 'Bistrô Horizonte', overview: 'Visão geral', reviews: 'Avaliações', whatsapp: 'WhatsApp', illustration: 'Demonstração ilustrativa', radar: 'Radar do Binno', radarTitle: 'Tempo de espera pede atenção', radarBody: 'Três avaliações recentes referem demora no atendimento. Reveja a escala do almoço antes da próxima semana.', queue: 'Fila de respostas', waiting: '3 avaliações aguardam resposta', replySuggested: 'Resposta sugerida', useReply: 'Usar resposta', copied: 'Resposta pronta a colar', edit: 'Editar', skip: 'Saltar', openReview: 'Abrir avaliação no Google', reviewMessage: 'O atendimento demorou mais do que o esperado e ninguém explicou o que estava a acontecer.', strength: 'O que está a ajudar', fragility: 'O que está a fragilizar', volume: 'Volume de avaliações', volumeBody: '3 avaliações esta semana, média de 10', volumeAlert: 'Queda de 70% em relação à média das últimas oito semanas.', stars: 'Cada nota separada', starsBody: 'Cinco estrelas perderam força. Notas uma e duas cresceram no período.', qr: 'Do QR ao Google', topics: 'Temas mais citados', reputation: 'Reputação no Google', responseTime: 'Tempo médio de resposta', newReviews: 'Novas avaliações em 30 dias', plan: 'Plano de hoje', practice: 'Reforce fotografias do prato executivo. Surge entre os elogios recentes.', completeness: 'Completude do perfil', weekly: 'O que mudou na semana', whatsappTitle: 'Resumo no WhatsApp', whatsappBody: 'O Binno entrega o essencial para não precisar de procurar informação.', preferenceTitle: 'Escolha o que quer receber', recipient: 'WhatsApp do gestor', frequency: 'Frequência', weeklySummary: 'Resumo semanal', radarAlerts: 'Alertas do Radar', replyAlerts: 'Avaliações que pedem resposta', profileAlerts: 'Melhorias do Perfil do Google', preview: 'Pré-visualização da mensagem', previewBody: 'Esta semana: o atendimento continua a ser uma força. Tempo de espera surgiu em três avaliações. Reveja a fila de respostas e a escala do almoço.', saved: 'Preferências guardadas nesta demonstração.', details: 'Ver detalhes', sampleReviewer: 'Mariana Souza', replyExample: 'Mariana, lamentamos muito a sua experiência. Já estamos a rever a organização do atendimento nos horários mais movimentados. Obrigado por nos contar o que aconteceu.', onePriority: 'Uma prioridade útil de cada vez' },
  },
  en: {
    locale: 'en',
    nav: { howItWorks: 'How Binno advises', capabilities: 'What it tracks', price: 'Plan', demo: 'Demo', login: 'Log in', start: 'Get started' },
    hero: { eyebrow: 'BINNO FOR LOCAL BUSINESSES', title: 'Your reputation advisor on Google.', body: 'Binno follows your reviews, spots important changes and shows what to do to protect and strengthen how customers see your business.', primary: 'Get started', secondary: 'See Binno in action', trust: 'You review every reply and decide what to publish.' },
    maps: { eyebrow: 'WHEN GOOGLE MAPS IS A FRONT DOOR', title: 'Your business is found on Google. Your reputation helps customers choose.', body: 'Binno organizes reviews, profile information and signals that affect the experience of people who find you on Maps.', note: 'Complete information helps Google understand a business. More reviews and positive ratings can contribute to local presence, with no guarantee of position or outcome.', link: 'Read Google guidance', steps: [{ title: 'Google Maps', body: 'Customers find, compare and decide.' }, { title: 'Reputation', body: 'Reviews help shape that decision.' }, { title: 'Binno', body: 'Your advisor shows what to do now.' }] },
    alerts: { eyebrow: 'MONITORING', title: 'Do not be caught by surprise.', body: 'When Binno identifies a change worth attention, it explains the signal and points to the next useful action.', items: [{ title: 'An unusual decline', body: 'See when review volume or rating composition changes in a meaningful way.' }, { title: 'More low ratings', body: 'Understand when one and two star reviews begin to grow.' }, { title: 'A recurring negative theme', body: 'Connect comments to an operational issue before it repeats.' }] },
    whatsapp: { eyebrow: 'ADVICE WITHOUT ANOTHER SCREEN', title: 'You do not need time to use Binno.', body: 'Binno comes to your WhatsApp when there is something useful to decide and delivers a weekly summary when you need context.', items: ['What strengthened your reputation', 'What made the business more vulnerable', 'Reviews that need attention', 'One practical opportunity to act'], note: 'You choose the alerts, frequency and number that receives the follow-up.' },
    replies: { eyebrow: 'ASSISTED QUEUE', title: 'Reply to customers without stopping to think what to say.', body: 'Binno reads the comment, suggests a reply in the review language and prepares the path to the right review on Google.', note: 'You review, adjust if needed and publish. Binno never publishes replies on its own.', link: 'Read Google review guidance' },
    history: { eyebrow: 'REPUTATION READING', title: 'A good rating does not mean everything is fine.', body: 'Follow the story behind the average to understand whether your reputation is getting stronger or more vulnerable.', items: ['Review volume by period', 'Separate evolution from one to five stars', 'Comparison with earlier periods', 'Most cited themes and weekly changes'] },
    radar: { eyebrow: 'BINNO RADAR', title: 'Turn reviews into business decisions.', body: 'Your advisor separates what deserves protection from what needs to change, always with evidence and a possible action.', strengthTitle: 'What is helping', strengthBody: 'Identify recurring praise, products and aspects that deserve more visibility.', riskTitle: 'What is making you vulnerable', riskBody: 'Find recurring complaints and act on the process affecting customers.' },
    profile: { eyebrow: 'PROFILE PLAN', title: 'Keep your Business Profile current.', body: 'Binno turns best practices into one useful priority at a time.', items: ['Reply to important reviews', 'Update photos and information', 'Review business hours and details', 'Track QR opens and Google clicks'] },
    demo: { eyebrow: 'FULL DEMO', title: 'See how Binno advises a business in practice.', body: 'Explore a complete illustrative scenario: alert, Radar, reply queue, history and WhatsApp preferences.', primary: 'Explore the demo', label: 'Illustrative demo' },
    pricing: { eyebrow: 'BINNO PLAN', title: 'Reputation advice for your business every day.', body: 'A clear reading of Google, practical priorities and easier replies to manage.', cta: 'Get started', monthly: '/month', availableLabel: 'For businesses in Brazil', availableHint: 'We confirm where the business operates during sign-up and validate it at payment.', promoLabel: 'FOUNDING BATCH', promoNote: 'The first {vagas} subscriptions keep this price for as long as they stay active. After that, it goes back to R${regular}.' },
    footer: { body: 'Reputation advice for local businesses.', demo: 'Demo', terms: 'Terms', privacy: 'Privacy' },
    contacto: { rotulo: 'Chat on WhatsApp', rotuloCurto: 'Talk to Binno', mensagemDaVenda: 'Hi! I came from the Binno site and would like to understand how it works.', mensagemDoNegocio: 'Hi! I saw Binno on a review page and would like to know how it works for my business.' },
    cockpit: { business: 'Horizon Bistro', overview: 'Overview', reviews: 'Reviews', whatsapp: 'WhatsApp', illustration: 'Illustrative demo', radar: 'Binno Radar', radarTitle: 'Waiting time needs attention', radarBody: 'Three recent reviews mention slow service. Review the lunch shift before next week.', queue: 'Reply queue', waiting: '3 reviews are waiting for your reply', replySuggested: 'Suggested reply', useReply: 'Use reply', copied: 'Reply ready to paste', edit: 'Edit', skip: 'Skip', openReview: 'Open review on Google', reviewMessage: 'Service took longer than expected and nobody explained what was happening.', strength: 'What is helping', fragility: 'What is making you vulnerable', volume: 'Review volume', volumeBody: '3 reviews this week, average of 10', volumeAlert: 'A 70% drop compared with the previous eight week average.', stars: 'Each rating separately', starsBody: 'Five star reviews lost share. One and two star ratings grew in this period.', qr: 'From QR to Google', topics: 'Most cited themes', reputation: 'Google reputation', responseTime: 'Average reply time', newReviews: 'New reviews in 30 days', plan: 'Today\'s plan', practice: 'Add a recent photo of the executive lunch. It appears in recent praise.', completeness: 'Profile completeness', weekly: 'What changed this week', whatsappTitle: 'WhatsApp summary', whatsappBody: 'Binno delivers the essentials so you do not have to look for information.', preferenceTitle: 'Choose what you want to receive', recipient: 'Manager WhatsApp', frequency: 'Frequency', weeklySummary: 'Weekly summary', radarAlerts: 'Radar alerts', replyAlerts: 'Reviews needing a reply', profileAlerts: 'Business Profile improvements', preview: 'Message preview', previewBody: 'This week: service remains a strength. Waiting time appeared in three reviews. Review the reply queue and lunch shift.', saved: 'Preferences saved in this demo.', details: 'View details', sampleReviewer: 'Mariana Souza', replyExample: 'Mariana, we are very sorry about your experience. We are reviewing service organization during the busiest hours. Thank you for telling us what happened.', onePriority: 'One useful priority at a time' },
  },
};

export const getMarketingCopy = (locale: Locale): MarketingCopy => COPY[locale] ?? COPY.en;
