
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pczzswkydhdgxesvyfed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjenpzd2t5ZGhkZ3hlc3Z5ZmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0ODExMDAsImV4cCI6MjA2MjA1NzEwMH0.84KF5JMfC4Ttiny8AH-vWvNne-7O4qF3FSpqZZLMOO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
